
import { Trait, Talent, Protocol, Mutation } from './types';

export const TRAITS_CATALOG: Trait[] = [
    // Backgrounds (V28)
    { id: 'ex_militar', name: 'Ex-Militar / Contratista', type: 'Background', description: 'Uniforme desgastado y disciplina.', effect: 'Prof: Atletismo, Intimidación. Ventaja vs Miedo.', grantsProficiency: ['athletics', 'intimidation'] },
    { id: 'cientifico', name: 'Científico Renegado', type: 'Background', description: 'Bata reforzada y conocimientos.', effect: 'Prof: Ciencias, Medicina. Identifica anomalías sin tirar.', grantsProficiency: ['tech', 'medicine'] },
    { id: 'scavenger', name: 'Habitante del Yermo', type: 'Background', description: 'Superviviente nato.', effect: 'Prof: Sigilo, Supervivencia. Ventaja vs comida/agua podrida.', grantsProficiency: ['stealth', 'survival'] },
    { id: 'criminal', name: 'Criminal / Contrabandista', type: 'Background', description: 'Vida al margen.', effect: 'Prof: Engaño, Juego Manos. Conoce códigos criminales.', grantsProficiency: ['deception', 'sleight_hand'] },
    { id: 'medico_campo', name: 'Médico de Campo', type: 'Background', description: 'Salvar vidas bajo fuego.', effect: 'Prof: Medicina, Perspicacia. Estabiliza como Acción Bonus.', grantsProficiency: ['medicine', 'insight'] },
    { id: 'tecnologo', name: 'Tecnólogo del Reich', type: 'Background', description: 'Ingeniería avanzada.', effect: 'Prof: Investigación, Herramientas. Repara armas como Acción Bonus.', grantsProficiency: ['investigation', 'tech'] },
    { id: 'guia_local', name: 'Guía Local (Sherpa)', type: 'Background', description: 'Conoce los caminos.', effect: 'Prof: Supervivencia, Historia. Sexto sentido para peligros climáticos.', grantsProficiency: ['survival', 'history'] },
    { id: 'sacerdote', name: 'Sacerdote del Culto', type: 'Background', description: 'Fe en lo anómalo.', effect: 'Prof: Religión, Persuasión. Ventaja Carisma con fanáticos.', grantsProficiency: ['religion', 'persuasion'] },
    { id: 'cazador', name: 'Cazador de Bestias', type: 'Background', description: 'Trofeos y trampas.', effect: 'Prof: Naturaleza, Sigilo. Ventaja INT para saber debilidades.', grantsProficiency: ['nature', 'stealth'] },
    { id: 'rata_tunel', name: 'Rata de Túnel', type: 'Background', description: 'Vida subterránea.', effect: 'Prof: Acrobacias, Percepción. Sin desventaja en espacios estrechos.', grantsProficiency: ['acrobatics', 'perception'] },
    { id: 'mensajero', name: 'Mensajero de la Zona', type: 'Background', description: 'La velocidad es vida.', effect: 'Prof: Atletismo, Acrobacias. +5 pies Vel si no llevas pesada.', grantsProficiency: ['athletics', 'acrobatics'] },
    { id: 'cocinero', name: 'Cocinero de Anomalías', type: 'Background', description: 'Sabe qué se come.', effect: 'Prof: Supervivencia, Utensilios. Comida cura 1d4 extra.', grantsProficiency: ['survival'] },
    { id: 'psiquico', name: 'Psíquico Latente', type: 'Background', description: 'La Zona te habla.', effect: 'Prof: Percepción, Engaño. Detecta anomalías 30 pies (dolor cabeza).', grantsProficiency: ['perception', 'deception'] },
    { id: 'arquitecto', name: 'Arquitecto de Refugios', type: 'Background', description: 'Refuerza estructuras.', effect: 'Prof: Investigación, Herramientas. Fortifica puertas (+5 CD).', grantsProficiency: ['investigation'] },
    { id: 'comerciante', name: 'Comerciante Itinerante', type: 'Background', description: 'El dinero mueve la Zona.', effect: 'Prof: Persuasión, Tasación. Sabe valor exacto de objetos.', grantsProficiency: ['persuasion'] },

    // Positive Traits
    { id: 'trait_alert', name: 'Alerta', type: 'Positive', description: 'Siempre vigilante.', effect: '+5 Iniciativa. No puedes ser sorprendido.' },
    { id: 'trait_lucky', name: 'Afortunado', type: 'Positive', description: 'El destino te sonríe.', effect: 'Puedes repetir 1 tirada de ataque pifia (1 natural) por día.' },
    { id: 'trait_ambidextrous', name: 'Ambidextro', type: 'Positive', description: 'Hábil con ambas manos.', effect: '+1 al Daño con armas en mano torpe.' },
    { id: 'trait_iron_stomach', name: 'Estómago de Hierro', type: 'Positive', description: 'Digestion robusta.', effect: 'Ventaja en salvaciones contra veneno ingerido.' },
    { id: 'trait_light_sleeper', name: 'Sueño Ligero', type: 'Positive', description: 'Te despiertas al instante.', effect: 'Sin penalización Percepción durmiendo.' },
    { id: 'trait_brawler', name: 'Peleador Callejero', type: 'Positive', description: 'Experto en bares.', effect: 'Puños hacen 1d4 daño.' },
    { id: 'trait_night_owl', name: 'Nocturno', type: 'Positive', description: 'Mejor de noche.', effect: 'Tratas luz tenue como brillante.' },
    { id: 'trait_charismatic', name: 'Líder Nato', type: 'Positive', description: 'Voz de mando.', effect: '+1 a Persuasión e Intimidación.' },
    { id: 'trait_mechanic', name: 'Manitas', type: 'Positive', description: 'Habilidad mecánica.', effect: 'Ventaja reparar objetos mecánicos.' },
    { id: 'trait_scout', name: 'Explorador', type: 'Positive', description: 'Ojo para el terreno.', effect: 'Ignoras terreno difícil natural.' },

    // Negative Traits
    { id: 'trait_fragile', name: 'Huesos de Cristal', type: 'Negative', description: 'Estructura ósea débil.', effect: '-10 lbs Carga Máxima. +1000 EA.' },
    { id: 'trait_hemophilia', name: 'Hemofilia', type: 'Negative', description: 'La sangre no coagula.', effect: 'Sangrado hace 1d6 daño. +1000 EA.' },
    { id: 'trait_insomnia', name: 'Insomnio', type: 'Negative', description: 'Mal descanso.', effect: 'Recuperas mitad DG en descanso largo. +1000 EA.' },
    { id: 'trait_paranoid', name: 'Paranoia', type: 'Negative', description: 'No confías en nadie.', effect: 'Desventaja Perspicacia. +1000 EA.' },
    { id: 'trait_one_eyed', name: 'Tuerto', type: 'Negative', description: 'Perdiste un ojo.', effect: 'Desventaja ataque rango >60ft. +1000 EA.' },
    { id: 'trait_clumsy', name: 'Torpe', type: 'Negative', description: 'Manos de mantequilla.', effect: '-2 Sigilo/Juego Manos. +1000 EA.' },
    { id: 'trait_coward', name: 'Cobarde', type: 'Negative', description: 'Pánico fácil.', effect: 'Desventaja salvaciones Miedo. +1000 EA.' },
    { id: 'trait_wanted', name: 'Buscado', type: 'Negative', description: 'Recompensa.', effect: 'Hostilidad en asentamientos. +1000 EA.' },
    { id: 'trait_claustrophobia', name: 'Claustrofobia', type: 'Negative', description: 'Pánico encierro.', effect: 'Desventaja en túneles. +1000 EA.' },
    { id: 'trait_addict', name: 'Adicto', type: 'Negative', description: 'Dependencia.', effect: 'Consumo diario o Fatiga. +1000 EA.' },
    { id: 'trait_pacifist', name: 'Pacifista', type: 'Negative', description: 'Aversión violencia.', effect: 'Desventaja daño letal humanoides. +1000 EA.' },
];

export const TALENTS_CATALOG: Talent[] = [
    // TANK (V28)
    { id: 'tank_tier1_1', name: 'Piel de Mutante', type: 'Tank', tier: 1, description: 'Tu piel es como cuero.', benefit: '+1 CA natural.', cost: 1000 },
    { id: 'tank_tier1_2', name: 'Provocación Táctica', type: 'Tank', tier: 1, description: 'Llamas la atención.', benefit: 'Enemigo a 9m debe atacarte o Desventaja.', cost: 1000 },
    { id: 'tank_tier1_3', name: 'Rompe-Líneas', type: 'Tank', tier: 1, description: 'Fuerza imparable.', benefit: 'Ventaja en Atletismo (Fuerza).', cost: 1000 },
    { id: 'tank_tier1_4', name: 'Resistencia al Dolor', type: 'Tank', tier: 1, description: 'Nervios amortiguados.', benefit: 'Ventaja Salv CON vs Fatiga.', cost: 1000 },
    { id: 'tank_tier1_5', name: 'Impacto Cinético', type: 'Tank', tier: 1, description: 'Sabes caer.', benefit: '-5 Daño Caída. Reacción reduce Contundente 1d4.', cost: 1000 },
    { id: 'tank_tier1_6', name: 'Metabolismo de Acero', type: 'Tank', tier: 1, description: 'Filtros industriales.', benefit: 'Ventaja Salv vs Veneno/Enfermedad.', cost: 1000 },
    { id: 'tank_tier1_7', name: 'Pies de Plomo', type: 'Tank', tier: 1, description: 'Inamovible.', benefit: 'Ventaja vs Derribo/Empujón.', cost: 1000 },
    { id: 'tank_tier1_8', name: 'Grito de Guerra', type: 'Tank', tier: 1, description: 'Inspiras valor.', benefit: 'Acción: Otorga HP Temp a aliado.', cost: 1000 },
    { id: 'tank_tier1_9', name: 'Freno de Boca', type: 'Tank', tier: 1, description: 'Aguantas el disparo.', benefit: 'Reduce daño de arma de fuego a quemarropa.', cost: 1000 },
    
    { id: 'tank_tier2_1', name: 'Escudo de Esencia', type: 'Tank', tier: 2, description: 'Aura repele energía.', benefit: 'Resistencia a 1 elemento. +1 Ranura Artefacto.', cost: 3000 },
    { id: 'tank_tier2_2', name: 'Regeneración Emergencia', type: 'Tank', tier: 2, description: 'Metabolismo forzado.', benefit: 'Acción: Gasta 2 DG para curarte ya.', cost: 3000 },
    { id: 'tank_tier2_3', name: 'Presencia Intimidante', type: 'Tank', tier: 2, description: 'Muerte encarnada.', benefit: 'Enemigos <50% HP tienen Desventaja al atacarte.', cost: 3000 },
    { id: 'tank_tier2_4', name: 'Arresto Táctico', type: 'Tank', tier: 2, description: 'Prensa hidráulica.', benefit: 'Presa a 2 objetivos con Ventaja.', cost: 3000 },
    { id: 'tank_tier2_5', name: 'Absorción de Esencia', type: 'Tank', tier: 2, description: 'Te alimentas del fallo.', benefit: 'Si fallan por poco, recuperas 1 HP.', cost: 3000 },
    { id: 'tank_tier2_6', name: 'Competencia Adicional', type: 'Tank', tier: 2, description: 'Entrenamiento extra.', benefit: 'Arma marcial extra o sin desventaja sigilo pesada.', cost: 3000 },

    { id: 'tank_tier3_1', name: 'Bastión Inquebrantable', type: 'Tank', tier: 3, description: 'Objeto inamovible.', benefit: 'Inmune Derribo. Estabilizas auto a 0 HP.', cost: 6000 },
    { id: 'tank_tier3_2', name: 'Guardián de la Zona', type: 'Tank', tier: 3, description: 'Instinto protector.', benefit: 'Reacción: Recibes el daño de un aliado adyacente.', cost: 6000 },
    { id: 'tank_tier3_3', name: 'Muro de Acero', type: 'Tank', tier: 3, description: 'Segunda piel.', benefit: 'Con Pesada, reduces daño físico no mágico en 3.', cost: 6000 },

    // DPS (V28)
    { id: 'dps_tier1_1', name: 'Ojo de Halcón', type: 'DPS', tier: 1, description: 'Zoom biológico.', benefit: 'Mitad penalización rango largo. Ventaja Percepción visual.', cost: 1000 },
    { id: 'dps_tier1_2', name: 'Disparo de Precisión', type: 'DPS', tier: 1, description: 'Buscas huecos.', benefit: 'Bonus: +Ataque, -Daño.', cost: 1000 },
    { id: 'dps_tier1_3', name: 'Recarga Rápida', type: 'DPS', tier: 1, description: 'Manos borrosas.', benefit: 'Recarga como Acción Bonificada.', cost: 1000 },
    { id: 'dps_tier1_4', name: 'Pistolero Nato', type: 'DPS', tier: 1, description: 'Extensión del puño.', benefit: '+1 Pistolas. Sin desventaja a 5 pies.', cost: 1000 },
    { id: 'dps_tier1_5', name: 'Reflejos de Serpiente', type: 'DPS', tier: 1, description: 'Overclock nervioso.', benefit: 'Suma PB a Iniciativa.', cost: 1000 },
    { id: 'dps_tier1_6', name: 'Asesino Silencioso', type: 'DPS', tier: 1, description: 'Daño silencioso.', benefit: '+1d4 daño con armas silenciadas.', cost: 1000 },
    { id: 'dps_tier1_7', name: 'Tirador Experto', type: 'DPS', tier: 1, description: 'Maestría fusiles.', benefit: '+1 Ataque Rifles/DMR.', cost: 1000 },
    { id: 'dps_tier1_8', name: 'Doble Disparo', type: 'DPS', tier: 1, description: 'Arma secundaria.', benefit: 'Bonus: Ataque extra con pistola mano torpe.', cost: 1000 },
    { id: 'dps_tier1_9', name: 'Manos Ágiles', type: 'DPS', tier: 1, description: 'Dedos de ladrón.', benefit: 'Ventaja Juego de Manos.', cost: 1000 },

    { id: 'dps_tier2_1', name: 'Descarga de Adrenalina', type: 'DPS', tier: 2, description: 'Ralentiza el mundo.', benefit: 'Acción: 2 ataques extra. Luego Fatiga.', cost: 3000 },
    { id: 'dps_tier2_2', name: 'Perforador Anómalo', type: 'DPS', tier: 2, description: 'Vibración destructiva.', benefit: 'Suma mitad PB al daño vs armadura.', cost: 3000 },
    { id: 'dps_tier2_3', name: 'Movimiento Fantasma', type: 'DPS', tier: 2, description: 'Dispara y desvanece.', benefit: 'Moverse tras atacar no provoca oportunidad.', cost: 3000 },
    { id: 'dps_tier2_4', name: 'Tiro Letal', type: 'DPS', tier: 2, description: 'Órganos vitales.', benefit: 'Críticos tiran un dado extra de daño.', cost: 3000 },
    { id: 'dps_tier2_5', name: 'Especialista Munición', type: 'DPS', tier: 2, description: 'Modificar balas.', benefit: 'HP gana penetración de AP y viceversa.', cost: 3000 },

    { id: 'dps_tier3_1', name: 'Maestro Ráfagas', type: 'DPS', tier: 3, description: 'Control retroceso.', benefit: 'Penalización Auto/Ráfaga a la mitad.', cost: 6000 },
    { id: 'dps_tier3_2', name: 'Instinto Asesino', type: 'DPS', tier: 3, description: 'Sangre llama sangre.', benefit: 'Matar otorga mover y ataque extra (Reacción).', cost: 6000 },
    { id: 'dps_tier3_3', name: 'Danza de la Muerte', type: 'DPS', tier: 3, description: 'Trauma masivo.', benefit: 'Acertar todo un turno aturde al enemigo.', cost: 6000 },

    // SUPPORT (V28)
    { id: 'supp_tier1_1', name: 'Resistencia Anomalías', type: 'Support', tier: 1, description: 'ADN reparador.', benefit: 'Ventaja Salv vs Radiación/Veneno anómalo.', cost: 1000 },
    { id: 'supp_tier1_2', name: 'Técnico de Campo', type: 'Support', tier: 1, description: 'Manos rápidas.', benefit: 'Usa Kit Médico/Mecánico como Bonus.', cost: 1000 },
    { id: 'supp_tier1_3', name: 'Pulso Vital', type: 'Support', tier: 1, description: 'Canaliza energía.', benefit: 'Acción: Cura 1d8. Estabiliza auto.', cost: 1000 },
    { id: 'supp_tier1_4', name: 'Ojo del Supervisor', type: 'Support', tier: 1, description: 'Ves patrones.', benefit: 'Ventaja Percepción/Investigación trampas.', cost: 1000 },
    { id: 'supp_tier1_5', name: 'Alquimia Rápida', type: 'Support', tier: 1, description: 'Mezcla y aplica.', benefit: 'Administra poción como acción rápida.', cost: 1000 },
    { id: 'supp_tier1_6', name: 'Conocimiento Prohibido', type: 'Support', tier: 1, description: 'Archivos secretos.', benefit: 'Prof: Arcano, Historia o Religión.', cost: 1000 },
    { id: 'supp_tier1_7', name: 'Escudo Esencia Menor', type: 'Support', tier: 1, description: 'Aura protege.', benefit: 'Resistencia a 1 daño elemental por día.', cost: 1000 },
    { id: 'supp_tier1_8', name: 'Vínculo Anómalo', type: 'Support', tier: 1, description: 'Simbiosis.', benefit: 'Si llevas Artefacto, recuperas 1 HP/turno.', cost: 1000 },
    { id: 'supp_tier1_9', name: 'Red de Seguridad', type: 'Support', tier: 1, description: 'Nadie atrás.', benefit: 'Reacción: Gasta DG para curar aliado a 0 HP.', cost: 1000 },

    { id: 'supp_tier2_1', name: 'Mente Sincronizada', type: 'Support', tier: 2, description: 'Nodo conexión.', benefit: '+1 Ranura Artefacto. Comparte pasivas artefactos.', cost: 3000 },
    { id: 'supp_tier2_2', name: 'Intervención Crítica', type: 'Support', tier: 2, description: 'Advertencia psíquica.', benefit: 'Permite a aliado repetir salvación fallida.', cost: 3000 },
    { id: 'supp_tier2_3', name: 'Sanador de Combate', type: 'Support', tier: 2, description: 'Curas potentes.', benefit: 'Suma PB a cura si objetivo tiene 0 HP.', cost: 3000 },
    { id: 'supp_tier2_4', name: 'Conjuración Emergencia', type: 'Support', tier: 2, description: 'Sobrecarga.', benefit: 'Lanza Hechizo Nv1 gratis 1/día.', cost: 3000 },
    { id: 'supp_tier2_5', name: 'Ingenio Anómalo', type: 'Support', tier: 2, description: 'Aprendizaje.', benefit: 'Mejoras de Habilidad cuestan 500 EA menos.', cost: 3000 },
    { id: 'supp_tier2_6', name: 'Mano Lejana', type: 'Support', tier: 2, description: 'Proyección.', benefit: 'Rango curas/toque aumenta a 30 pies.', cost: 3000 },

    { id: 'supp_tier3_1', name: 'Fuente de Esencia', type: 'Support', tier: 3, description: 'Reactor viviente.', benefit: 'Recupera EA. Aliados +1 Salvaciones.', cost: 6000 },
    { id: 'supp_tier3_2', name: 'Poder de la Zona', type: 'Support', tier: 3, description: 'Zona obedece.', benefit: 'Ventaja Concentración. +1 Ranura Artefacto. Ignora armadura.', cost: 6000 },
    { id: 'supp_tier3_3', name: 'Resurrección Limitada', type: 'Support', tier: 3, description: 'Desafía muerte.', benefit: 'Revive muerto reciente con 1 HP.', cost: 6000 },

    // GENERAL
    { id: 'gen_mule', name: 'Mula de Carga', type: 'General', tier: 1, description: 'Espalda fuerte.', benefit: '+20 lbs Carga.', cost: 1000 },
    { id: 'gen_runner', name: 'Corredor', type: 'General', tier: 1, description: 'Piernas fuertes.', benefit: '+5 pies Velocidad.', cost: 1000 },
    { id: 'gen_negotiator', name: 'Negociador', type: 'General', tier: 1, description: 'Lengua de plata.', benefit: 'Ventaja en Persuasión y Engaño.', cost: 1000 },
    { id: 'gen_tough', name: 'Duro de Matar', type: 'General', tier: 2, description: 'Aguante sobrenatural.', benefit: '+2 HP por nivel.', cost: 2000 },
    { id: 'gen_stealth', name: 'Sombra', type: 'General', tier: 2, description: 'Invisibilidad práctica.', benefit: 'Esconderse como acción bonus.', cost: 2000 },
    { id: 'gen_parkour', name: 'Parkour', type: 'General', tier: 2, description: 'Movilidad urbana.', benefit: 'Ignoras terreno difícil no mágico.', cost: 2000 },
];

export const PROTOCOLS_CATALOG: Protocol[] = [
    // Nivel 0 (Trucos)
    { id: 'proto_resist', name: 'Estimulante de Resistencia', level: 0, school: 'Abjuración', castingTime: '1 Acción', range: 'Toque', description: 'Refuerza sinapsis.', effect: '+1d4 a una Salvación.' },
    { id: 'proto_ward', name: 'Endurecimiento Dérmico', level: 0, school: 'Abjuración', castingTime: '1 Acción', range: 'Personal', description: 'Piel dura como granito.', effect: 'Resistencia daño físico 1 turno.' },
    { id: 'proto_sanctity', name: 'Sello de Plomo Menor', level: 0, school: 'Abjuración', castingTime: '1 Acción', range: 'Toque', description: 'Zona muerta de información.', effect: 'Indetectable sensores/cámaras.' },
    { id: 'proto_deflect', name: 'Deflector de Escombros', level: 0, school: 'Abjuración', castingTime: 'Reacción', range: 'Personal', description: 'Almohadilla de aire.', effect: 'Reduce daño objeto pequeño a 0.' },
    { id: 'proto_light', name: 'Linterna Química', level: 0, school: 'Evocación', castingTime: '1 Acción', range: 'Toque', description: 'Fotones visibles.', effect: 'Luz brillante 20 pies.' },
    { id: 'proto_shock', name: 'Taser de Contacto', level: 0, school: 'Evocación', castingTime: '1 Acción', range: 'Toque', description: 'Carga estática.', effect: '1d8 Eléctrico. Quita reacción.' },
    { id: 'proto_frost', name: 'Rayo Criogénico', level: 0, school: 'Evocación', castingTime: '1 Acción', range: '60 pies', description: 'Roba calor.', effect: '1d8 Frío. -10 pies velocidad.' },
    { id: 'proto_firebolt', name: 'Disparo Incendiario', level: 0, school: 'Evocación', castingTime: '1 Acción', range: '120 pies', description: 'Esfera plasma.', effect: '1d10 Fuego.' },
    { id: 'proto_thunder', name: 'Detonador Sónico', level: 0, school: 'Evocación', castingTime: '1 Acción', range: '5 pies', description: 'Onda choque.', effect: '1d6 Trueno (Área).' },
    { id: 'proto_magehand', name: 'Brazo Manipulador', level: 0, school: 'Conjuración', castingTime: '1 Acción', range: '30 pies', description: 'Distorsión gravitatoria.', effect: 'Manipula objetos (10 lbs).' },
    { id: 'proto_poison', name: 'Dardo Tóxico', level: 0, school: 'Conjuración', castingTime: '1 Acción', range: '10 pies', description: 'Nube corrosiva.', effect: '1d12 Veneno.' },
    { id: 'proto_acid', name: 'Vial de Ácido', level: 0, school: 'Conjuración', castingTime: '1 Acción', range: '60 pies', description: 'Glóbulo ácido.', effect: '1d6 Ácido (1 o 2 obj).' },
    { id: 'proto_bonfire', name: 'Bengala Térmica', level: 0, school: 'Conjuración', castingTime: '1 Acción', range: '60 pies', description: 'Ignición espontánea.', effect: '1d8 Fuego (Cubo 5ft).' },
    { id: 'proto_infest', name: 'Nanocápsula de Enjambre', level: 0, school: 'Conjuración', castingTime: '1 Acción', range: '30 pies', description: 'Parásitos energía.', effect: '1d6 Veneno + Mover 5ft.' },
    { id: 'proto_true', name: 'Cálculo Balístico', level: 0, school: 'Adivinación', castingTime: '1 Acción', range: '30 pies', description: 'Vectores movimiento.', effect: 'Ventaja primer ataque sig. turno.' },
    { id: 'proto_guide', name: 'Asistente IA', level: 0, school: 'Adivinación', castingTime: '1 Acción', range: 'Toque', description: 'Presciencia menor.', effect: '+1d4 a prueba Habilidad.' },
    { id: 'proto_analyze', name: 'Escaneo Rápido', level: 0, school: 'Adivinación', castingTime: '1 Acción', range: 'Toque', description: 'Estructura atómica.', effect: 'Lectura física detallada.' },
    { id: 'proto_sense', name: 'Detector Anomalías', level: 0, school: 'Adivinación', castingTime: '1 Acción', range: 'Personal', description: 'Zumbido dientes.', effect: 'Alerta presencia anómala 30ft.' },
    { id: 'proto_cipher', name: 'Lectura de Labios', level: 0, school: 'Adivinación', castingTime: '1 Acción', range: 'Visual', description: 'Micro-vibraciones.', effect: 'Entiendes habla visual.' },
    { id: 'proto_mock', name: 'Insulto Psíquico', level: 0, school: 'Encantamiento', castingTime: '1 Acción', range: '60 pies', description: 'Glitch cerebral.', effect: '1d4 Psíquico + Desventaja ataque.' },
    { id: 'proto_friend', name: 'Feromonas Sintéticas', level: 0, school: 'Encantamiento', castingTime: '1 Acción', range: 'Personal', description: 'Aura confianza.', effect: 'Ventaja Carisma (Hostil al acabar).' },
    { id: 'proto_sliver', name: 'Pico Neuronal', level: 0, school: 'Encantamiento', castingTime: '1 Acción', range: '60 pies', description: 'Aguja mental.', effect: '1d6 Psíquico -1d4 Salv.' },
    { id: 'proto_encode', name: 'Encriptar Memoria', level: 0, school: 'Encantamiento', castingTime: '1 Acción', range: 'Personal', description: 'Hilo luz sólida.', effect: 'Pensamiento a objeto físico.' },
    { id: 'proto_command0', name: 'Orden Menor', level: 0, school: 'Encantamiento', castingTime: '1 Acción', range: '30 pies', description: 'Empujón mental.', effect: 'Bestia obedece orden básica.' },
    { id: 'proto_illusion', name: 'Holo-Proyector', level: 0, school: 'Ilusión', castingTime: '1 Acción', range: '30 pies', description: 'Imagen estática.', effect: 'Imagen simple o sonido.' },
    { id: 'proto_ghost', name: 'Señuelo de Audio', level: 0, school: 'Ilusión', castingTime: '1 Acción', range: '30 pies', description: 'Ventrílocuo.', effect: 'Voces lejanas.' },
    { id: 'proto_disguise0', name: 'Camuflaje Facial', level: 0, school: 'Ilusión', castingTime: '1 Acción', range: 'Personal', description: 'Distorsión rasgos.', effect: 'Cambias cara.' },
    { id: 'proto_blur', name: 'Ruido Blanco Visual', level: 0, school: 'Ilusión', castingTime: '1 Acción', range: 'Toque', description: 'Pixelación.', effect: 'Hace ilegible texto.' },
    { id: 'proto_foot', name: 'Falso Rastro', level: 0, school: 'Ilusión', castingTime: '1 Acción', range: '30 pies', description: 'Huellas térmicas.', effect: 'Rastro falso.' },
    { id: 'proto_chill', name: 'Toque Entrópico', level: 0, school: 'Necromancia', castingTime: '1 Acción', range: '120 pies', description: 'Mano espectral.', effect: '1d8 Necrótico. Impide cura.' },
    { id: 'proto_spare', name: 'Estabilizador', level: 0, school: 'Necromancia', castingTime: '1 Acción', range: 'Toque', description: 'Choque vital.', effect: 'Estabiliza a 0 HP.' },
    { id: 'proto_toll', name: 'Frecuencia Mortal', level: 0, school: 'Necromancia', castingTime: '1 Acción', range: '60 pies', description: 'Campana fúnebre.', effect: 'Alto daño Necrótico si herido.' },
    { id: 'proto_sap', name: 'Drenaje', level: 0, school: 'Necromancia', castingTime: '1 Acción', range: '30 pies', description: 'Roba cinética.', effect: '1d4 Necrótico + Prone.' },
    { id: 'proto_decomp', name: 'Descomponer', level: 0, school: 'Necromancia', castingTime: '1 Acción', range: 'Toque', description: 'Acelera entropía.', effect: 'Cadáver a hueso.' },
    { id: 'proto_msg_c', name: 'Radio Cifrada', level: 0, school: 'Transmutación', castingTime: '1 Acción', range: '120 pies', description: 'Voz a mente.', effect: 'Susurro distancia.' },
    { id: 'proto_mend_c', name: 'Soldador', level: 0, school: 'Transmutación', castingTime: '1 Minuto', range: 'Toque', description: 'Fusiona bordes.', effect: 'Repara roturas.' },
    { id: 'proto_presti', name: 'Multi-Herramienta', level: 0, school: 'Transmutación', castingTime: '1 Acción', range: '10 pies', description: 'Alteraciones locales.', effect: 'Limpiar, calentar, marcar.' },
    { id: 'proto_whip', name: 'Cable de Arrastre', level: 0, school: 'Transmutación', castingTime: '1 Acción', range: '30 pies', description: 'Látigo energía.', effect: '1d6 Daño + Atrae 10ft.' },
    { id: 'proto_shill', name: 'Bastón Cargado', level: 0, school: 'Transmutación', castingTime: 'Bonus', range: 'Toque', description: 'Imbuye madera.', effect: 'Arma mágica d8.' },

    // Nivel 1
    { id: 'proto_lock', name: 'Cierre de Emergencia', level: 1, school: 'Abjuración', castingTime: '1 Acción', range: 'Toque', description: 'Sello físico.', effect: 'Traba puerta.' },
    { id: 'proto_shield', name: 'Campo de Fuerza', level: 1, school: 'Abjuración', castingTime: 'Reacción', range: 'Personal', description: 'Barrera hexagonal.', effect: '+5 CA. Anula proyectiles.' },
    { id: 'proto_prot', name: 'Sello de Plomo', level: 1, school: 'Abjuración', castingTime: '1 Acción', range: 'Toque', description: 'Ruido blanco psíquico.', effect: 'Desventaja Aberraciones.' },
    { id: 'proto_absorb', name: 'Absorción de Energía', level: 1, school: 'Abjuración', castingTime: 'Reacción', range: 'Personal', description: 'Pararrayos anómalo.', effect: 'Resistencia elemental + Daño.' },
    { id: 'proto_armor', name: 'Blindaje de Piel', level: 1, school: 'Abjuración', castingTime: '1 Acción', range: 'Toque', description: 'Tensión superficial.', effect: 'CA 13 + Dex.' },
    { id: 'proto_grease', name: 'Grasa Industrial', level: 1, school: 'Conjuración', castingTime: '1 Acción', range: '60 pies', description: 'Ectoplasma resbaladizo.', effect: 'Área resbaladiza.' },
    { id: 'proto_fog', name: 'Nube de Humo', level: 1, school: 'Conjuración', castingTime: '1 Acción', range: '120 pies', description: 'Vapor denso.', effect: 'Oscurecimiento total.' },
    { id: 'proto_mark', name: 'Marcador Táctico', level: 1, school: 'Adivinación', castingTime: 'Bonus', range: '90 pies', description: 'Firma vital.', effect: '+1d6 Daño. Rastreo.' },
    { id: 'proto_det', name: 'Escáner de Amenazas', level: 1, school: 'Adivinación', castingTime: '1 Acción', range: 'Personal', description: 'Tercer ojo.', effect: 'Detecta Aberraciones/No-Muertos.' },
    { id: 'proto_ident', name: 'Identificar', level: 1, school: 'Adivinación', castingTime: '1 Minuto', range: 'Toque', description: 'Comunión psíquica.', effect: 'Revela propiedades.' },
    { id: 'proto_comm', name: 'Orden Imperativa', level: 1, school: 'Encantamiento', castingTime: '1 Acción', range: '60 pies', description: 'Autoridad psíquica.', effect: 'Obedece 1 palabra.' },
    { id: 'proto_laugh', name: 'Gas de la Risa', level: 1, school: 'Encantamiento', castingTime: '1 Acción', range: '30 pies', description: 'Sobrecarga euforia.', effect: 'Prone e Incapacitado.' },
    { id: 'proto_hero', name: 'Inyección de Valor', level: 1, school: 'Encantamiento', castingTime: '1 Acción', range: 'Toque', description: 'Bloquea miedo.', effect: 'Inmune Miedo. HP Temp.' },
    { id: 'proto_missile', name: 'Micro-Cohetes', level: 1, school: 'Evocación', castingTime: '1 Acción', range: '120 pies', description: 'Dardos fuerza.', effect: '3x (1d4+1). Auto.' },
    { id: 'proto_burn', name: 'Lanzallamas', level: 1, school: 'Evocación', castingTime: '1 Acción', range: 'Cono 15ft', description: 'Abanico fuego.', effect: '3d6 Fuego.' },
    { id: 'proto_wave', name: 'Onda Sónica', level: 1, school: 'Evocación', castingTime: '1 Acción', range: 'Cubo 15ft', description: 'Explosión aire.', effect: '2d8 Trueno + Empuje.' },
    { id: 'proto_bolt', name: 'Proyectil de Plasma', level: 1, school: 'Evocación', castingTime: '1 Acción', range: '120 pies', description: 'Trazador energía.', effect: '4d6 Radiante. Ventaja sig. ataque.' },
    { id: 'proto_disg', name: 'Holo-Disfraz', level: 1, school: 'Ilusión', castingTime: '1 Acción', range: 'Personal', description: 'Capa holográfica.', effect: 'Cambia apariencia.' },
    { id: 'proto_silent', name: 'Señuelo', level: 1, school: 'Ilusión', castingTime: '1 Acción', range: '60 pies', description: 'Holograma 3D.', effect: 'Imagen móvil.' },
    { id: 'proto_inflict', name: 'Toque de la Muerte', level: 1, school: 'Necromancia', castingTime: '1 Acción', range: 'Toque', description: 'Entropía pura.', effect: '3d10 Necrótico.' },
    { id: 'proto_false', name: 'Falsa Vida', level: 1, school: 'Necromancia', castingTime: '1 Acción', range: 'Personal', description: 'Energía anómala.', effect: '1d4+4 HP Temp.' },
    { id: 'proto_sanc', name: 'Baliza de Protección', level: 1, school: 'Abjuración', castingTime: 'Bonus', range: '30 pies', description: 'Campo apatía.', effect: 'Enemigo salva SAB para atacar.' },
    { id: 'proto_feath', name: 'Caída de Pluma', level: 1, school: 'Transmutación', castingTime: 'Reacción', range: '60 pies', description: 'Gravedad personal.', effect: 'Caída lenta.' },
    { id: 'proto_jump', name: 'Salto Asistido', level: 1, school: 'Transmutación', castingTime: '1 Acción', range: 'Toque', description: 'Potencia piernas.', effect: 'Triple salto.' },

    // Nivel 2
    { id: 'proto_lock2', name: 'Cierre Electrónico', level: 2, school: 'Abjuración', castingTime: '1 Acción', range: 'Toque', description: 'Reescribe realidad puerta.', effect: 'Bloqueo permanente (+10 CD).' },
    { id: 'proto_rest', name: 'Restauración Sistema', level: 2, school: 'Abjuración', castingTime: '1 Acción', range: 'Toque', description: 'Quema toxinas.', effect: 'Cura condición.' },
    { id: 'proto_misty', name: 'Salto de Fase', level: 2, school: 'Conjuración', castingTime: 'Bonus', range: 'Personal', description: 'Dimensión bolsillo.', effect: 'Teleport 30ft.' },
    { id: 'proto_web', name: 'Espuma de Contención', level: 2, school: 'Conjuración', castingTime: '1 Acción', range: '60 pies', description: 'Hebras pegajosas.', effect: 'Red atrapa enemigos.' },
    { id: 'proto_spir', name: 'Dron de Asalto', level: 2, school: 'Conjuración', castingTime: 'Bonus', range: '60 pies', description: 'Constructo fuerza.', effect: 'Ataque 1d8+Mod.' },
    { id: 'proto_see', name: 'Visión Térmica', level: 2, school: 'Adivinación', castingTime: '1 Acción', range: 'Personal', description: 'Espectro completo.', effect: 'Ver invisible.' },
    { id: 'proto_thoughts', name: 'Escáner Mental', level: 2, school: 'Adivinación', castingTime: '1 Acción', range: 'Personal', description: 'Sintoniza Noosfera.', effect: 'Lee pensamientos.' },
    { id: 'proto_locate', name: 'Localizar Objeto', level: 2, school: 'Adivinación', castingTime: '1 Acción', range: 'Personal', description: 'Radar mental.', effect: 'Dirección objeto.' },
    { id: 'proto_sugg', name: 'Sugestión', level: 2, school: 'Encantamiento', castingTime: '1 Acción', range: '30 pies', description: 'Reescribe prioridad.', effect: 'Sigue instrucción 8h.' },
    { id: 'proto_hold', name: 'Parálisis Táctica', level: 2, school: 'Encantamiento', castingTime: '1 Acción', range: '60 pies', description: 'Corta conexión motora.', effect: 'Paralizado.' },
    { id: 'proto_zone', name: 'Zona de Verdad', level: 2, school: 'Encantamiento', castingTime: '1 Acción', range: '60 pies', description: 'Presión mental.', effect: 'No mentiras.' },
    { id: 'proto_scorch', name: 'Rayo Abrasador', level: 2, school: 'Evocación', castingTime: '1 Acción', range: '120 pies', description: 'Láseres.', effect: '3 rayos 2d6 Fuego.' },
    { id: 'proto_dark', name: 'Oscuridad', level: 2, school: 'Evocación', castingTime: '1 Acción', range: '60 pies', description: 'Vacío fotónico.', effect: 'Oscuridad total.' },
    { id: 'proto_inv', name: 'Camuflaje Óptico', level: 2, school: 'Ilusión', castingTime: '1 Acción', range: 'Toque', description: 'Dobla luz.', effect: 'Invisible.' },
    { id: 'proto_silence', name: 'Silenciador', level: 2, school: 'Ilusión', castingTime: '1 Acción', range: '120 pies', description: 'Vacío auditivo.', effect: 'Silencio total.' },
    { id: 'proto_mirror', name: 'Doble Digital', level: 2, school: 'Ilusión', castingTime: '1 Acción', range: 'Personal', description: 'Ecos temporales.', effect: 'Duplicados absorben.' },
    { id: 'proto_enfeeble', name: 'Rayo Debilitante', level: 2, school: 'Necromancia', castingTime: '1 Acción', range: '60 pies', description: 'Atrofia músculos.', effect: 'Mitad daño fuerza.' },
    { id: 'proto_magicw', name: 'Arma Anómala', level: 2, school: 'Transmutación', castingTime: '1 Acción', range: 'Toque', description: 'Vibra energía.', effect: 'Arma +1.' },
    { id: 'proto_levi', name: 'Levitar', level: 2, school: 'Transmutación', castingTime: '1 Acción', range: '60 pies', description: 'Anula gravedad.', effect: 'Flotar 20ft.' },
    { id: 'proto_darkv', name: 'Visión Nocturna', level: 2, school: 'Transmutación', castingTime: '1 Acción', range: 'Toque', description: 'Altera retinas.', effect: 'Visión oscuridad.' },

    // Nivel 3
    { id: 'proto_count', name: 'Contramedida EMP', level: 3, school: 'Abjuración', castingTime: 'Reacción', range: '60 pies', description: 'Pulso negación.', effect: 'Interrumpe hechizo.' },
    { id: 'proto_dispel', name: 'Disipador Anomalías', level: 3, school: 'Abjuración', castingTime: '1 Acción', range: '120 pies', description: 'Arranca hilos.', effect: 'Termina efectos.' },
    { id: 'proto_circle', name: 'Círculo Aislamiento', level: 3, school: 'Abjuración', castingTime: '1 Minuto', range: '10 pies', description: 'Límite matemático.', effect: 'Bloquea Aberraciones.' },
    { id: 'proto_hut', name: 'Búnker Portátil', level: 3, school: 'Abjuración', castingTime: '1 Minuto', range: 'Personal', description: 'Burbuja espacio-tiempo.', effect: 'Cúpula segura 8h.' },
    { id: 'proto_stink', name: 'Nube Tóxica', level: 3, school: 'Conjuración', castingTime: '1 Acción', range: '90 pies', description: 'Gas sulfúrico.', effect: 'Náuseas.' },
    { id: 'proto_thunderstep', name: 'Transposición Sónica', level: 3, school: 'Conjuración', castingTime: '1 Acción', range: '90 pies', description: 'Colapso espacio.', effect: 'Teleport + Daño.' },
    { id: 'proto_conjure', name: 'Torreta Automática', level: 3, school: 'Conjuración', castingTime: '1 Acción', range: '60 pies', description: 'Luz dura.', effect: 'Invoca aliados.' },
    { id: 'proto_fireball', name: 'Granada de Vacío', level: 3, school: 'Evocación', castingTime: '1 Acción', range: '150 pies', description: 'Singularidad térmica.', effect: '8d6 Fuego (20ft).' },
    { id: 'proto_lightn', name: 'Cañón de Riel', level: 3, school: 'Evocación', castingTime: '1 Acción', range: 'Línea 100ft', description: 'Arco voltaico.', effect: '8d6 Eléctrico.' },
    { id: 'proto_anim', name: 'Reanimación', level: 3, school: 'Necromancia', castingTime: '1 Minuto', range: '10 pies', description: 'Falsa vida.', effect: 'Crea Zombie/Esqueleto.' },
    { id: 'proto_reviv', name: 'Desfibrilador', level: 3, school: 'Necromancia', castingTime: '1 Acción', range: 'Toque', description: 'Descarga masiva.', effect: 'Revive reciente.' },
    { id: 'proto_vamp', name: 'Toque Vampírico', level: 3, school: 'Necromancia', castingTime: '1 Acción', range: 'Personal', description: 'Succión vida.', effect: 'Drena HP.' },
    { id: 'proto_haste', name: 'Acelerar', level: 3, school: 'Transmutación', castingTime: '1 Acción', range: '30 pies', description: 'Flujo temporal.', effect: 'Doble vel, +2 CA, Acción.' },
    { id: 'proto_slow', name: 'Lentitud', level: 3, school: 'Transmutación', castingTime: '1 Acción', range: '120 pies', description: 'Espesa tiempo.', effect: 'Mitad vel, -2 CA.' },
    { id: 'proto_fly', name: 'Volar', level: 3, school: 'Transmutación', castingTime: '1 Acción', range: 'Toque', description: 'Vuelo verdadero.', effect: 'Vuelo 60ft.' },

    // Nivel 4
    { id: 'proto_stone', name: 'Piel de Grafeno', level: 4, school: 'Abjuración', castingTime: '1 Acción', range: 'Toque', description: 'Carbono cristalino.', effect: 'Resistencia físico.' },
    { id: 'proto_dim', name: 'Puerta de Gusano', level: 4, school: 'Conjuración', castingTime: '1 Acción', range: '500 pies', description: 'Pliega espacio.', effect: 'Teleport 500ft.' },
    { id: 'proto_eye', name: 'Ojo Espía', level: 4, school: 'Adivinación', castingTime: '1 Acción', range: '30 pies', description: 'Fragmento consciencia.', effect: 'Sensor remoto.' },
    { id: 'proto_conf', name: 'Confusión', level: 4, school: 'Encantamiento', castingTime: '1 Acción', range: '90 pies', description: 'Desorden sináptico.', effect: 'Caos cognitivo.' },
    { id: 'proto_wallf', name: 'Muro de Fuego', level: 4, school: 'Evocación', castingTime: '1 Acción', range: '120 pies', description: 'Plasma sostenido.', effect: 'Muro daño.' },
    { id: 'proto_ice', name: 'Tormenta de Hielo', level: 4, school: 'Evocación', castingTime: '1 Acción', range: '300 pies', description: 'Granizo anómalo.', effect: 'Daño mixto.' },
    { id: 'proto_ginv', name: 'Camuflaje Mayor', level: 4, school: 'Ilusión', castingTime: '1 Acción', range: 'Toque', description: 'Invisibilidad avanzada.', effect: 'Invisible atacando.' },
    { id: 'proto_phant', name: 'Pesadilla', level: 4, school: 'Ilusión', castingTime: '1 Acción', range: '120 pies', description: 'Miedo primitivo.', effect: 'Daño Psíquico.' },
    { id: 'proto_blight', name: 'Plaga', level: 4, school: 'Necromancia', castingTime: '1 Acción', range: '30 pies', description: 'Drena agua.', effect: '8d8 Necrótico.' },
    { id: 'proto_poly', name: 'Polimorfar', level: 4, school: 'Transmutación', castingTime: '1 Acción', range: '60 pies', description: 'Reescribe biología.', effect: 'Transforma en bestia.' },

    // Nivel 5+
    { id: 'proto_rest5', name: 'Restablecimiento Mayor', level: 5, school: 'Abjuración', castingTime: '1 Acción', range: 'Toque', description: 'Copia seguridad.', effect: 'Elimina efectos severos.' },
    { id: 'proto_cloud', name: 'Nube de la Muerte', level: 5, school: 'Conjuración', castingTime: '1 Acción', range: '120 pies', description: 'Niebla corrosiva.', effect: '5d8 Veneno.' },
    { id: 'proto_telep', name: 'Enlace de Datos', level: 5, school: 'Adivinación', castingTime: '1 Acción', range: '30 pies', description: 'Red neuronal.', effect: 'Telepatía grupal.' },
    { id: 'proto_dom5', name: 'Dominar Mente', level: 5, school: 'Encantamiento', castingTime: '1 Acción', range: '60 pies', description: 'Suprime consciencia.', effect: 'Control total.' },
    { id: 'proto_telek', name: 'Telequinesis', level: 5, school: 'Transmutación', castingTime: '1 Acción', range: '60 pies', description: 'Fuerza bruta mental.', effect: 'Mover objetos.' },
    { id: 'proto_wallth', name: 'Muro de Alambre', level: 6, school: 'Conjuración', castingTime: '1 Acción', range: '120 pies', description: 'Fractales afilados.', effect: 'Muro daño cortante.' },
    { id: 'proto_truev', name: 'Visión Verdadera', level: 6, school: 'Adivinación', castingTime: '1 Acción', range: 'Toque', description: 'Código fuente.', effect: 'Ver realidad.' },
    { id: 'proto_sun', name: 'Rayo Solar', level: 6, school: 'Evocación', castingTime: '1 Acción', range: 'Línea 60ft', description: 'Láser estelar.', effect: '6d8 Radiante.' },
    { id: 'proto_disint', name: 'Desintegrar', level: 6, school: 'Transmutación', castingTime: '1 Acción', range: '60 pies', description: 'Rompe enlaces.', effect: 'Daño masivo/polvo.' },
    { id: 'proto_simul', name: 'Simulacro', level: 7, school: 'Ilusión', castingTime: '12 Horas', range: 'Toque', description: 'Materia moldeada.', effect: 'Copia perfecta.' },
    { id: 'proto_pain', name: 'Palabra de Dolor', level: 7, school: 'Encantamiento', castingTime: '1 Acción', range: '60 pies', description: 'Receptores al máximo.', effect: 'Desventaja total.' },
    { id: 'proto_clone', name: 'Clon', level: 8, school: 'Necromancia', castingTime: '1 Hora', range: 'Toque', description: 'Recipiente inerte.', effect: 'Cuerpo repuesto.' },
    { id: 'proto_fore', name: 'Presagio de Combate', level: 9, school: 'Adivinación', castingTime: '1 Minuto', range: 'Toque', description: 'Tiempo no lineal.', effect: 'Ventaja en todo.' },
    { id: 'proto_time', name: 'Parar el Tiempo', level: 9, school: 'Transmutación', castingTime: '1 Acción', range: 'Personal', description: 'Fuera de flujo.', effect: 'Turnos extra.' },
];

export const MUTATIONS_CATALOG: Mutation[] = [
    { id: 'mut_glass_skin', name: 'Piel de Vidrio', type: 'Corporeal', effect: 'Ventaja en Intimidación. Competencia en Salv. Constitución.', downside: 'Vulnerable a daño Contundente.' },
    { id: 'mut_photosensitivity', name: 'Fotosensibilidad', type: 'Corporeal', effect: 'Visión Oscura 60ft.', downside: 'Desventaja bajo luz solar directa.' },
    { id: 'mut_furnace', name: 'Metabolismo Horno', type: 'Corporeal', effect: 'Inmune al frío natural.', downside: 'Requiere x4 comida/agua o ganas Fatiga.' },
    { id: 'mut_acid_blood', name: 'Sangre Ácida', type: 'Corporeal', effect: 'Al recibir daño físico, 1d4 ácido a 5 pies.', downside: 'Dañas tu propia armadura (reparación costosa).' },
    { id: 'mut_whispers', name: 'Susurros', type: 'Psionic', effect: 'Inmune a Sorpresa.', downside: 'Desventaja en Concentración.' },
    { id: 'mut_magnetism', name: 'Magnetismo', type: 'Cosmic', effect: '+1 CA contra armas de fuego.', downside: '-1 Sigilo si llevas metal.' },
    { id: 'mut_spider_fingers', name: 'Dedos Arácnidos', type: 'Corporeal', effect: 'Ventaja Juego de Manos.', downside: 'Desventaja armas pequeñas.' },
    { id: 'mut_static_aura', name: 'Aura Estática', type: 'Cosmic', effect: 'Resistencia Eléctrica.', downside: 'Dañas electrónica cercana.' },
    { id: 'mut_hollow_bones', name: 'Huesos de Pájaro', type: 'Corporeal', effect: '+10ft Velocidad.', downside: '-2 Salvaciones Fuerza. Carga a la mitad.' },
    { id: 'mut_bark_skin', name: 'Piel Corteza', type: 'Corporeal', effect: 'CA Base 13 + Des (max 2).', downside: 'Desventaja Acrobacias.' },
    { id: 'mut_gills', name: 'Branquias', type: 'Corporeal', effect: 'Inmune gases.', downside: 'Desventaja respirando aire limpio prolongado.' },
    { id: 'mut_living_shadow', name: 'Sombra Viva', type: 'Cosmic', effect: 'Ventaja Sigilo (oscuro).', downside: 'Desventaja Iniciativa.' },
    { id: 'mut_phase', name: 'Desfase', type: 'Cosmic', effect: 'Teleport 15ft (bonus).', downside: 'Recibes 1d6 daño al usarlo.' },
    { id: 'mut_prey_scent', name: 'Olor de Presa', type: 'Corporeal', effect: 'Ventaja rastrear.', downside: 'Mutantes te focusean.' },
    { id: 'mut_reactor_heart', name: 'Corazón Reactor', type: 'Corporeal', effect: 'Inmune Radiación.', downside: 'Irradias a aliados cercanos.' },
    { id: 'mut_addiction', name: 'Adicción', type: 'Corporeal', effect: 'Comes EA en vez de comida.', downside: 'Coste mantenimiento elevado.' },
    { id: 'mut_radio_voice', name: 'Voz Radio', type: 'Psionic', effect: 'Hablas por radio mental.', downside: 'Voz normal suena mal.' },
    { id: 'mut_hive_mind', name: 'Mente Colmena', type: 'Psionic', effect: 'Detectas mutantes.', downside: 'Aturdido al matar.' },
    { id: 'mut_ascension', name: 'Ascensión', type: 'Psionic', effect: 'Gana +1 a un Stat.', downside: 'Tira dos veces en la tabla de mutaciones.' },
    { id: 'mut_telepathy', name: 'Telepatía Limitada', type: 'Psionic', effect: 'Comunicación mental 30 pies.', downside: 'Dolor de cabeza si hay mucha gente (Desventaja INT).' },
    { id: 'mut_foresight', name: 'Premonición', type: 'Psionic', effect: 'Añade 1d4 a la Iniciativa.', downside: 'Sufres flashbacks traumáticos (random).' },
    { id: 'mut_mental_static', name: 'Estática Mental', type: 'Psionic', effect: 'Enemigos tienen -1d4 a salvaciones mentales cerca de ti.', downside: 'No puedes dormir bien (recuperas menos dados de golpe).' },
    { id: 'mut_entropy_touch', name: 'Toque Entrópico', type: 'Cosmic', effect: 'Causas Necrótico en vez de contundente desarmado.', downside: 'La comida se pudre en tus manos.' },
    { id: 'mut_gravity_well', name: 'Pozo de Gravedad', type: 'Cosmic', effect: 'Puedes caminar por paredes.', downside: 'Velocidad reducida en terreno normal.' },
    { id: 'mut_claws', name: 'Garras Óseas', type: 'Corporeal', effect: 'Ataque desarmado hace 1d6 cortante.', downside: 'Dificultad manipulando objetos delicados.' },
    { id: 'mut_carapace', name: 'Caparazón Quitinoso', type: 'Corporeal', effect: 'Reduce daño cortante en 2.', downside: '-1 Destreza.' },
    { id: 'mut_regeneration', name: 'Regeneración', type: 'Corporeal', effect: 'Recuperas 1 HP al inicio de turno si tienes >0 HP.', downside: 'Vulnerable a Fuego. Requiere doble ración diaria.' },
    { id: 'mut_extra_arm', name: 'Brazo Extra', type: 'Corporeal', effect: 'Puedes interactuar con objetos como acción bonus.', downside: 'Cuesta encontrar armadura compatible (Coste x2).' },
    { id: 'mut_grave_touch', name: 'Toque de la Tumba', type: 'Cosmic', effect: 'Ataques desarmados causan 1d6 daño necrótico.', downside: 'Inmune a curación mágica (solo curas con descanso).' },
    { id: 'mut_compound_eyes', name: 'Ojos Compuestos', type: 'Corporeal', effect: 'Ventaja en Percepción visual, ves en 360°.', downside: 'Desventaja vs efectos que requieren "mirar" (ej. Medusa).' },
    { id: 'mut_venom_tongue', name: 'Lengua Venenosa', type: 'Corporeal', effect: 'Ataque mordida: 1d4 veneno + envenenado (Salv CON 13).', downside: 'No puedes comer comida normal (solo carne cruda).' },
    { id: 'mut_dermal_spines', name: 'Espinas Dérmicas', type: 'Corporeal', effect: 'Criaturas que te agarran reciben 1d4 perforante.', downside: '-1 CA (espinas interfieren con armadura).' },
    { id: 'mut_acid_glands', name: 'Glándulas Ácidas', type: 'Corporeal', effect: 'Escupir ácido: 30 pies, 2d6 ácido (Recarga 5-6).', downside: 'Tus dientes se corroen (dificultad para hablar).' },
    { id: 'mut_cold_blood', name: 'Sangre Helada', type: 'Corporeal', effect: 'Resistencia a Frío.', downside: 'Vulnerable a Fuego, movimiento lento en clima cálido.' },
    { id: 'mut_symbiote', name: 'Simbionte Parasitario', type: 'Corporeal', effect: '+2 Constitución mientras tengas >50% HP.', downside: 'Si llegas a 0 HP, pierdes mutación y 1d6 CON permanente.' },
    { id: 'mut_biosynthesizer', name: 'Órgano Biosintetizador', type: 'Corporeal', effect: 'Sintetizas agua pura (1 litro/día).', downside: 'Necesitas consumir material orgánico extra (musgo, plantas).' },
    { id: 'mut_chromatic_camo', name: 'Camuflaje Cromático', type: 'Corporeal', effect: 'Acción: Invisibilidad 1 min (Concentración), 1/descanso largo.', downside: 'Desnudo obligatorio (armadura rompe el efecto).' },
    { id: 'mut_seismic_sense', name: 'Sentido Sísmico', type: 'Cosmic', effect: '"Ves" por vibraciones en 30 pies (incluso ciego).', downside: 'Sordo a sonidos normales, dependes de vibración.' },
];
