
import { Weapon } from './types';

export const WEAPON_PROPERTIES_GLOSSARY = [
    { id: 'Fiable', desc: 'Inmune a efectos de agua/suciedad. Nunca pifia con 1 natural.' },
    { id: 'Bonificada', desc: 'Otorga +1 a las tiradas de ataque debido a su calidad de fabricación superior.' },
    { id: 'Auto', desc: 'Puedes realizar un ataque de área (Cubo 10ft) gastando 10 balas. Todos en el área hacen Salvación DEX CD 12 o reciben el daño.' },
    { id: 'Incontrolable', desc: 'Si te mueves en el mismo turno que disparas, tienes Desventaja en el ataque.' },
    { id: 'Inestable', desc: 'Al atacar (o recibir crítico), riesgo de efecto anómalo o daño al usuario.' },
    { id: 'Perforante', desc: '+1 al ataque contra enemigos con armadura ligera o piel natural gruesa.' },
    { id: 'Perforante Superior', desc: '+2 al ataque contra enemigos con armadura media o pesada.' },
    { id: 'Verdad Absoluta', desc: 'Ignora cualquier Resistencia al daño perforante (mágica o natural).' },
    { id: 'Ignorar Blindaje', desc: 'El objetivo no suma su bono de armadura a la CA (CA = 10 + Des).' },
    { id: 'Freno de Boca', desc: 'Permite volver a tirar los 1s en el daño.' },
    { id: 'Segunda Oportunidad', desc: '1 vez por combate, puedes repetir una tirada de ataque fallida.' },
    { id: 'Ligera', desc: 'Puede usarse en la mano torpe sin penalización para el combate con dos armas.' },
    { id: 'Silencio Total', desc: 'Los disparos son inaudibles a más de 30 pies.' },
    { id: 'Capa de Sombra', desc: 'Tras matar a un enemigo, te vuelves Invisible hasta el final de tu siguiente turno.' },
    { id: 'Modo Ráfaga', desc: 'Puedes hacer un ataque adicional como Acción Bonificada (con desventaja).' },
    { id: 'Orden de Fuego', desc: 'Dispara 3 balas por ataque. Tira ataque una vez, multiplica el daño por 3 si acierta.' },
    { id: 'Aura de Valor', desc: 'Eres inmune a la condición de Miedo mientras la empuñes.' },
    { id: 'Bajo Retroceso', desc: 'No tiene desventaja al disparar en combate cuerpo a cuerpo (5 pies).' },
    { id: 'Fiabilidad', desc: 'Inmune a efectos de agua/suciedad. Nunca pifia con 1 natural.' },
    { id: 'Oculta', desc: 'Ventaja en pruebas de Juego de Manos para esconderla.' },
    { id: 'Sigilo', desc: 'Con supresor, es inaudible a más de 10 pies. Daño bajo.' },
    { id: 'Ejecución', desc: 'Si el objetivo tiene menos de 15 HP tras el daño, muere instantáneamente.' },
    { id: 'Control', desc: 'Puedes repetir los dados de daño de 1 o 2 una vez por ataque.' },
    { id: 'Defensor', desc: '+1 al Ataque y Daño por cada turno consecutivo que no te muevas (Max +3).' },
    { id: 'Congelación', desc: 'Críticos infligen daño de Frío extra y reducen la velocidad del objetivo a la mitad.' },
    { id: 'Quirúrgico', desc: 'Puedes aceptar Desventaja en el ataque para asegurar un Crítico si aciertas.' },
    { id: 'Cargador Masivo', desc: 'Solo necesitas recargar tras 3 ataques críticos o pifias (abstracción).' },
    { id: 'Rebote', desc: 'Las balas fallidas pueden rebotar a un enemigo a 5 pies. Ignora cobertura media.' },
    { id: 'Parada', desc: '+2 daño a objetivos a menos de 15 pies (o si cargan contra ti).' },
    { id: 'Emboscada', desc: 'Ventaja en ataques contra enemigos que aún no te han atacado en el combate.' },
    { id: 'Super V', desc: 'No tiene desventaja al disparar ráfagas largas.' },
    { id: 'Lluvia', desc: 'Puedes atacar a 2 objetivos adyacentes con una sola acción (divide el daño).' },
    { id: 'Recarga Constante', desc: 'Debe recargar constantemente (capacidad baja).' },
    { id: 'Polvo y Silencio', desc: 'Disparos totalmente silenciosos. Si mata, no deja cuerpo (polvo).' },
    { id: 'Doble Cañón', desc: 'Puedes disparar ambos cañones a la vez para doble daño.' },
    { id: 'Onda de Choque', desc: 'El disparo doble empuja a los enemigos 10 pies hacia atrás.' },
    { id: 'Corredera', desc: 'Fiable. Cicla cualquier munición.' },
    { id: 'Breaching', desc: 'Ventaja y Doble daño contra puertas/estructuras.' },
    { id: 'Inevitable', desc: 'El daño ignora resistencias y escudos mágicos. +Daño Necrótico.' },
    { id: 'Semiauto', desc: 'Permite ataques de oportunidad.' },
    { id: 'Fuego', desc: 'Transmuta munición normal en conos de fuego (15 pies) sin coste extra.' },
    { id: 'Supresión', desc: 'Los enemigos impactados pierden 10 pies de movimiento (o desventaja).' },
    { id: 'Terror', desc: 'Impactos causan Miedo (Salvación de Sabiduría).' },
    { id: 'Fiabilidad Extrema', desc: 'Inmune a condiciones ambientales.' },
    { id: 'Impacto Masivo', desc: 'Derriba objetivos (Salv FUE). Retroceso brutal.' },
    { id: 'Suave', desc: 'Permite disparar dos veces sin penalización de retroceso.' },
    { id: 'Daño Continuo', desc: 'Dispara perdigones incendiarios que queman por turnos.' },
    { id: 'Penetración', desc: 'Ignora cobertura ligera.' },
    { id: 'Controlable', desc: 'Estándar 5.45. Muy controlable.' },
    { id: 'Compacto', desc: 'Versión compacta. Sin desventaja en espacios cerrados.' },
    { id: 'Ráfaga 2', desc: 'Puedes repetir 1 dado de daño por turno.' },
    { id: 'Luz Pura', desc: 'Daño Radiante. Silencioso.' },
    { id: 'Modular', desc: 'Cambia accesorios como acción bonificada.' },
    { id: 'Ergonómica', desc: 'Versión civil ergonómica.' },
    { id: 'Competición', desc: 'AR de competición. Precisión extrema, delicado.' },
    { id: 'Canalizar', desc: 'Gasta Spell Slots para añadir daño de Fuerza masivo.' },
    { id: 'Tiro de Rayo', desc: '1/combate daño eléctrico + Aturdir.' },
    { id: 'Fantasma', desc: 'Silenciosa. +2 daño a armaduras.' },
    { id: 'Asesino', desc: 'Doble Daño automático contra objetivos desprevenidos.' },
    { id: 'Potente', desc: 'Semiautomático .308. Potente para caza mayor.' },
    { id: 'Calibre Batalla', desc: 'Dado de daño aumentado (d10).' },
    { id: 'Cazador', desc: 'Ventaja contra criaturas Grandes, Enormes o Gargantuescas.' },
    { id: 'Indestructible', desc: 'Carabina antigua. Indestructible y barata.' },
    { id: 'Bullpup', desc: 'Sin desventaja en espacios estrechos.' },
    { id: 'Híbrido', desc: 'Puede usar cargadores de AK en emergencia.' },
    { id: 'Regeneración', desc: 'Recupera munición lentamente fuera de combate.' },
    { id: 'Resistencia', desc: 'Ganas resistencia al daño físico al disparar, pero Vel 0.' },
    { id: 'Infinita', desc: 'Nunca se sobrecalienta ni encasquilla. Fuego continuo.' },
    { id: 'Invisible', desc: 'Disparos sin fogonazo, humo ni trazadoras.' },
    { id: 'Retroceso Constante', desc: 'Moverse y disparar sin penalización.' },
    { id: 'Foco', desc: 'Disparar no rompe la Concentración en hechizos.' },
    { id: 'Letal', desc: 'Dragunov civil. Letal para caza.' },
    { id: 'Visión', desc: 'Ve a través de humo, niebla y oscuridad mágica.' },
    { id: 'Ventrílocuo', desc: 'El sonido se origina a 30m del tirador.' },
    { id: 'Silencioso', desc: 'Compatible con supresor sin perder rango.' },
    { id: 'Marcar', desc: 'Acción bonificada para dar Ventaja a aliados contra un objetivo.' },
    { id: 'Sub-MOA', desc: 'Precisión sub-MOA. El Ferrari de los DMR.' },
    { id: 'Alerta', desc: 'Inmune a Sorpresa.' },
    { id: 'Óptica', desc: 'Ignora penalización por cobertura media.' },
    { id: 'Simple', desc: 'Base popular. Acción simple.' },
    { id: 'Flotante', desc: 'Optimizado. Cañón flotante.' },
    { id: 'Militar', desc: 'Chasis militar. Cargadores extraíbles.' },
    { id: 'Parálisis', desc: 'Impactos pueden paralizar al objetivo (Salv CON).' },
    { id: 'Fantasma Ignora Cobertura', desc: 'Ignora Cobertura (atraviesa muros).' },
    { id: 'Cálculo', desc: 'Gasta turno completo para golpe automático (sin dados).' },
    { id: 'Fantasma Urbano', desc: 'Inaudible a >50 pies.' },
    { id: 'Silencio', desc: 'Crea zona de Silencio Mágico al disparar.' },
    { id: 'Olvido', desc: 'Víctimas inmunes a interrogatorio mágico.' },
    { id: 'Robusto', desc: 'Estándar ruso. Robusto.' },
    { id: 'Alcance Extremo', desc: 'Rango efectivo masivo.' },
    { id: 'Alcance', desc: 'Sin desventaja por rango largo.' },
    { id: 'Sin Caída', desc: 'Trayectoria recta infinita. Silencio.' },
    { id: 'Urbano', desc: 'Combate urbano.' },
    { id: 'Plegable', desc: 'Plegable. Destruye vehículos.' },
    { id: 'Demolición', desc: 'Destruye cobertura no mágica instantáneamente.' },
    { id: 'Anti-Estructura', desc: 'Doble daño a objetos.' },
    { id: 'Onda', desc: 'Impactos crean área de daño (5ft).' },
    { id: 'Obsoleto', desc: 'Antitanque obsoleto. Monotiro.' },
    { id: 'Perforador', desc: 'Atraviesa muros gruesos.' },
    { id: 'Explosivo', desc: 'Daño en área pequeña (5ft).' },
    { id: 'Plasma', desc: 'Carga tiro de energía pura.' },
    { id: 'Despejar', desc: 'Ventaja al cortar maleza o extremidades débiles.' },
    { id: 'Corte Profundo', desc: 'Crítico con 19-20 contra bestias.' },
    { id: 'Lento', desc: '-1 a la Iniciativa.' },
    { id: 'Tajo', desc: 'Hoja curva para tajos.' },
    { id: 'Rápida', desc: 'Ligera y rápida.' },
    { id: 'Nudillos', desc: 'Golpea y apuñala.' },
    { id: 'CQC', desc: 'Sin desventaja en espacios confinados.' },
    { id: 'Versátil', desc: 'Puede usarse a una o dos manos (d8/d10).' },
    { id: 'Anómalo', desc: 'Daño de Fuerza + Bono salvación.' },
    { id: 'Vampirismo', desc: 'Críticos curan al portador.' },
    { id: 'Rompe-Escudos', desc: 'Destruye escudos físicos y reduce la CA del objetivo.' },
    { id: 'Relámpago', desc: 'Puede lanzarse y regresa a la mano (daño eléctrico).' },
    { id: 'Gravedad', desc: 'Dispara rayo de Gravedad (aplastamiento).' },
    { id: 'Arco Voltaico', desc: 'Descarga Arco Voltaico (1/combate).' },
    { id: 'Congelar', desc: 'Cono de Frío Absoluto. Ralentiza.' },
];

export const WEAPONS_CATALOG: Weapon[] = [
  // --- PISTOLAS ---
  { id: 'glock17', name: 'Glock 17/19', type: 'Pistola', damage: '1d6', damageType: 'Perforante', range: '30/90', weight: 1.5, price: 2500, rarity: 'Civil', properties: ['Fiable', 'Bonificada'] },
  { id: 'glock18c', name: 'Glock 18c', type: 'Pistola', damage: '1d6', damageType: 'Perforante', range: '20/60', weight: 1.8, price: 40000, rarity: 'Táctica', properties: ['Auto', 'Incontrolable'] },
  { id: 'fallo_cinderfall', name: 'Fallo de Cinderfall', type: 'Pistola', damage: '1d6', damageType: 'Fuerza', range: '60/120', weight: 1.5, price: 0, rarity: 'Legendaria', properties: ['Munición Infinita', 'Inestable'] },
  { id: 'tokarev', name: 'Tokarev TT', type: 'Pistola', damage: '1d8', damageType: 'Perforante', range: '40/120', weight: 1.9, price: 800, rarity: 'Civil', properties: ['Perforante'] },
  { id: 'clavo_comisario', name: 'El Clavo del Comisario', type: 'Pistola', damage: '1d8', damageType: 'Perforante', range: '50/150', weight: 1.9, price: 0, rarity: 'Legendaria', properties: ['Verdad Absoluta'] },
  { id: 'm1911', name: 'M1911 (.45)', type: 'Pistola', damage: '1d6+2', damageType: 'Perforante', range: '30/90', weight: 2.4, price: 2000, rarity: 'Civil', properties: ['Bonificada'] },
  { id: 'm1911_tac', name: 'M1911 Táctica', type: 'Pistola', damage: '1d6+2', damageType: 'Perforante', range: '40/120', weight: 2.6, price: 6500, rarity: 'Táctica', properties: ['Freno de Boca'] },
  { id: 'bala_aitos', name: 'La Última Bala de Aitos', type: 'Pistola', damage: '1d6+2', damageType: 'Perforante', range: '40/120', weight: 2.4, price: 0, rarity: 'Legendaria', properties: ['Segunda Oportunidad'] },
  { id: 'makarov', name: 'Makarov PM', type: 'Pistola', damage: '1d6', damageType: 'Perforante', range: '20/60', weight: 1.6, price: 600, rarity: 'Civil', properties: ['Ligera'] },
  { id: 'makarov_pb', name: 'Makarov PB', type: 'Pistola', damage: '1d6', damageType: 'Perforante', range: '30/90', weight: 2.1, price: 3000, rarity: 'Táctica', properties: ['Silencio Total'] },
  { id: 'susurro_fantasma', name: 'Susurro del Fantasma', type: 'Pistola', damage: '1d6', damageType: 'Perforante', range: '30/90', weight: 2.0, price: 0, rarity: 'Legendaria', properties: ['Capa de Sombra'] },
  { id: 'stechkin', name: 'Stechkin APS', type: 'Pistola', damage: '1d6', damageType: 'Perforante', range: '40/120', weight: 2.7, price: 11000, rarity: 'Táctica', properties: ['Modo Ráfaga'] },
  { id: 'furia_general', name: 'La Furia del General', type: 'Pistola', damage: '1d6', damageType: 'Perforante', range: '40/120', weight: 2.5, price: 0, rarity: 'Legendaria', properties: ['Orden de Fuego'] },
  { id: 'beretta', name: 'Beretta M9', type: 'Pistola', damage: '1d6', damageType: 'Perforante', range: '40/120', weight: 2.1, price: 2300, rarity: 'Civil', properties: ['Bonificada'] },
  { id: 'deber_centurion', name: 'El Deber del Centurión', type: 'Pistola', damage: '1d6', damageType: 'Perforante', range: '40/120', weight: 2.1, price: 0, rarity: 'Legendaria', properties: ['Aura de Valor'] },
  { id: 'fiveseven', name: 'FN Five-seveN', type: 'Pistola', damage: '1d8', damageType: 'Perforante', range: '50/150', weight: 1.3, price: 15000, rarity: 'Táctica', properties: ['Perforante Superior'] },
  { id: 'abrelatas', name: 'El Abrelatas', type: 'Pistola', damage: '1d8', damageType: 'Perforante', range: '50/150', weight: 1.5, price: 0, rarity: 'Legendaria', properties: ['Ignorar Blindaje'] },
  { id: 'rhino', name: 'Revolver Rhino 60DS', type: 'Pistola', damage: '1d10', damageType: 'Perforante', range: '40/120', weight: 2.0, price: 3000, rarity: 'Civil', properties: ['Bajo Retroceso'] },
  { id: 'p226', name: 'Pistola P226R', type: 'Pistola', damage: '1d6', damageType: 'Perforante', range: '40/120', weight: 1.9, price: 7000, rarity: 'Táctica', properties: ['Fiabilidad'] },
  { id: 'derringer', name: 'Derringer', type: 'Pistola', damage: '1d4', damageType: 'Perforante', range: '10/30', weight: 0.5, price: 200, rarity: 'Civil', properties: ['Oculta'] },
  { id: 'ruger', name: 'Ruger Mark IV', type: 'Pistola', damage: '1d4', damageType: 'Perforante', range: '50/150', weight: 1.8, price: 450, rarity: 'Civil', properties: ['Sigilo'] },
  { id: 'ultimo_argumento', name: 'El Último Argumento', type: 'Pistola', damage: '2d12', damageType: 'Contundente', range: '30/90', weight: 4.5, price: 0, rarity: 'Legendaria', properties: ['Ejecución'] },

  // --- SUBFUSILES ---
  { id: 'mp5', name: 'MP5 (SP5)', type: 'Subfusil', damage: '1d8', damageType: 'Perforante', range: '50/150', weight: 5.5, price: 5000, rarity: 'Civil', properties: ['Estándar'] },
  { id: 'mp5a3', name: 'MP5A3', type: 'Subfusil', damage: '1d8', damageType: 'Perforante', range: '60/180', weight: 6.8, price: 20000, rarity: 'Táctica', properties: ['Control'] },
  { id: 'eco_asedio', name: 'Eco del Asedio', type: 'Subfusil', damage: '1d8', damageType: 'Perforante', range: '60/180', weight: 6.5, price: 0, rarity: 'Legendaria', properties: ['Defensor'] },
  { id: 'vityaz', name: 'Vityaz-SN', type: 'Subfusil', damage: '1d8', damageType: 'Perforante', range: '50/150', weight: 6.4, price: 18000, rarity: 'Táctica', properties: ['Robusta'] },
  { id: 'frio_petersburgo', name: 'El Frío de San Petersburgo', type: 'Subfusil', damage: '1d8', damageType: 'Perforante', range: '50/150', weight: 6.4, price: 0, rarity: 'Legendaria', properties: ['Congelación'] },
  { id: 'mp7', name: 'MP7', type: 'Subfusil', damage: '1d6', damageType: 'Perforante', range: '40/120', weight: 4.1, price: 35000, rarity: 'Táctica', properties: ['Perforante'] },
  { id: 'aguja_cirujano', name: 'La Aguja del Cirujano', type: 'Subfusil', damage: '1d6', damageType: 'Perforante', range: '40/120', weight: 4.2, price: 0, rarity: 'Legendaria', properties: ['Quirúrgico'] },
  { id: 'p90', name: 'P90', type: 'Subfusil', damage: '1d8', damageType: 'Perforante', range: '60/200', weight: 5.7, price: 38000, rarity: 'Táctica', properties: ['Cargador Masivo'] },
  { id: 'zumbido_colmena', name: 'El Zumbido de la Colmena', type: 'Subfusil', damage: '1d8', damageType: 'Perforante', range: '60/200', weight: 5.7, price: 0, rarity: 'Legendaria', properties: ['Rebote'] },
  { id: 'ump_c', name: 'UMP (Civil)', type: 'Subfusil', damage: '1d6+2', damageType: 'Perforante', range: '50/150', weight: 5.0, price: 4500, rarity: 'Civil', properties: ['Pesada'] },
  { id: 'ump_t', name: 'UMP (Táctica)', type: 'Subfusil', damage: '1d6+2', damageType: 'Perforante', range: '60/180', weight: 5.0, price: 14000, rarity: 'Táctica', properties: ['Parada'] },
  { id: 'pacificador', name: 'El Pacificador', type: 'Subfusil', damage: '1d6+2', damageType: 'Perforante', range: '60/180', weight: 5.0, price: 0, rarity: 'Legendaria', properties: ['Emboscada'] },
  { id: 'mp9', name: 'MP9', type: 'Subfusil', damage: '1d6', damageType: 'Perforante', range: '30/90', weight: 3.0, price: 19000, rarity: 'Táctica', properties: ['Bonificada', 'Dispersión'] },
  { id: 'vector', name: 'Vector (.45 ACP)', type: 'Subfusil', damage: '1d6+2', damageType: 'Perforante', range: '50/150', weight: 6.0, price: 42000, rarity: 'Táctica', properties: ['Super V'] },
  { id: 'ppsh', name: 'PPSh-41', type: 'Subfusil', damage: '1d8', damageType: 'Perforante', range: '40/120', weight: 8.0, price: 4000, rarity: 'Táctica', properties: ['Lluvia'] },
  { id: 'uzi', name: 'Micro Uzi', type: 'Subfusil', damage: '1d6', damageType: 'Perforante', range: '30/90', weight: 4, price: 1500, rarity: 'Civil', properties: ['Auto', 'Ligera'] },

  // --- ESCOPETAS ---
  { id: 'toz106', name: 'TOZ-106', type: 'Escopeta', damage: '1d8', damageType: 'Contundente', range: '15/30', weight: 5.5, price: 500, rarity: 'Civil', properties: ['Recarga Constante'] },
  { id: 'desesperacion_huerfano', name: 'La Desesperación del Huérfano', type: 'Escopeta', damage: '1d8', damageType: 'Contundente', range: '15/30', weight: 5.5, price: 0, rarity: 'Legendaria', properties: ['Polvo y Silencio'] },
  { id: 'spr310', name: 'SPR310', type: 'Escopeta', damage: '1d8', damageType: 'Contundente', range: '20/60', weight: 7.0, price: 1200, rarity: 'Caceria', properties: ['Doble Cañón'] },
  { id: 'rugido_guardabosques', name: 'El Rugido del Guardabosques', type: 'Escopeta', damage: '1d8', damageType: 'Contundente', range: '20/60', weight: 7.0, price: 0, rarity: 'Legendaria', properties: ['Onda de Choque'] },
  { id: 'm870_c', name: 'M870 (Civil)', type: 'Escopeta', damage: '1d8', damageType: 'Contundente', range: '20/60', weight: 7.5, price: 1800, rarity: 'Civil', properties: ['Corredera'] },
  { id: 'm870_ca', name: 'M870 (Caza)', type: 'Escopeta', damage: '1d8', damageType: 'Contundente', range: '40/80', weight: 8.0, price: 2500, rarity: 'Caceria', properties: ['Precisión'] },
  { id: 'm870_t', name: 'M870 (Táctica)', type: 'Escopeta', damage: '1d8', damageType: 'Contundente', range: '20/60', weight: 7.0, price: 6000, rarity: 'Táctica', properties: ['Breaching'] },
  { id: 'fantasma_trinchera', name: 'El Fantasma de la Trinchera', type: 'Escopeta', damage: '1d8', damageType: 'Contundente', range: '20/60', weight: 7.0, price: 0, rarity: 'Legendaria', properties: ['Inevitable'] },
  { id: 'mp153_c', name: 'MP-153 (Civil)', type: 'Escopeta', damage: '1d8', damageType: 'Contundente', range: '30/90', weight: 8.0, price: 2200, rarity: 'Civil', properties: ['Semiauto'] },
  { id: 'mp153_ca', name: 'MP-153 (Caza)', type: 'Escopeta', damage: '1d8', damageType: 'Contundente', range: '40/100', weight: 8.5, price: 3000, rarity: 'Caceria', properties: ['Precisa'] },
  { id: 'mp153_t', name: 'MP-153 (Táctica)', type: 'Escopeta', damage: '1d8', damageType: 'Contundente', range: '30/90', weight: 8.2, price: 8000, rarity: 'Táctica', properties: ['Semiauto'] },
  { id: 'respiracion_dragon', name: 'La Respiración del Dragón', type: 'Escopeta', damage: '1d8', damageType: 'Fuego', range: '15 (Cono)', weight: 8.2, price: 0, rarity: 'Legendaria', properties: ['Fuego'] },
  { id: 'saiga12_c', name: 'Saiga-12 (Civil)', type: 'Escopeta', damage: '1d8', damageType: 'Contundente', range: '30/90', weight: 8.0, price: 4000, rarity: 'Civil', properties: ['Cargador'] },
  { id: 'saiga12_t', name: 'Saiga-12 (Táctica)', type: 'Escopeta', damage: '1d8', damageType: 'Contundente', range: '30/90', weight: 8.5, price: 16000, rarity: 'Táctica', properties: ['Supresión'] },
  { id: 'martillo_kult', name: 'El Martillo del Kult', type: 'Escopeta', damage: '1d8', damageType: 'Contundente', range: '30/90', weight: 8.5, price: 0, rarity: 'Legendaria', properties: ['Terror'] },
  { id: 'benelli', name: 'Benelli M4', type: 'Escopeta', damage: '1d8', damageType: 'Contundente', range: '30/90', weight: 8.4, price: 25000, rarity: 'Táctica', properties: ['Fiabilidad Extrema'] },
  { id: 'ks23', name: 'KS-23 (Cal 4)', type: 'Escopeta', damage: '3d8', damageType: 'Contundente', range: '40/120', weight: 10.0, price: 10000, rarity: 'Táctica', properties: ['Impacto Masivo'] },
  { id: 'remington1100', name: 'Remington 1100', type: 'Escopeta', damage: '1d8', damageType: 'Contundente', range: '40/100', weight: 7.5, price: 2800, rarity: 'Caceria', properties: ['Suave'] },
  { id: 'corazon_fuego', name: 'Corazón de Fuego', type: 'Escopeta', damage: '1d8', damageType: 'Fuego', range: '30/90', weight: 8.2, price: 0, rarity: 'Legendaria', properties: ['Daño Continuo'] },
  { id: 'recortada', name: 'Recortada', type: 'Escopeta', damage: '2d8', damageType: 'Perforante', range: '15/30', weight: 4, price: 400, rarity: 'Chatarra', properties: ['Dispersión', 'Oculta'] },

  // --- RIFLES DE ASALTO ---
  { id: 'saiga_vepr_akm', name: 'Saiga/Vepr (AKM)', type: 'Rifle Asalto', damage: '2d6', damageType: 'Perforante', range: '80/240', weight: 7.7, price: 3500, rarity: 'Civil', properties: ['Semiauto'] },
  { id: 'saiga_vepr_ak74', name: 'Saiga/Vepr (AK-74)', type: 'Rifle Asalto', damage: '1d8', damageType: 'Perforante', range: '100/300', weight: 7.5, price: 4000, rarity: 'Civil', properties: ['Preciso'] },
  { id: 'akm', name: 'AKM', type: 'Rifle Asalto', damage: '2d6', damageType: 'Perforante', range: '80/240', weight: 8.0, price: 12000, rarity: 'Táctica', properties: ['Penetración'] },
  { id: 'ak74', name: 'AK-74', type: 'Rifle Asalto', damage: '1d8', damageType: 'Perforante', range: '100/300', weight: 7.8, price: 15000, rarity: 'Táctica', properties: ['Controlable'] },
  { id: 'ak105', name: 'Serie 100 / AK-105', type: 'Rifle Asalto', damage: '1d8', damageType: 'Perforante', range: '90/270', weight: 7.0, price: 22000, rarity: 'Táctica', properties: ['Compacto'] },
  { id: 'ak12', name: 'AK-12', type: 'Rifle Asalto', damage: '1d8', damageType: 'Perforante', range: '90/270', weight: 7.5, price: 30000, rarity: 'Táctica', properties: ['Ráfaga 2'] },
  { id: 'fantasma_cinderfall', name: 'Fantasma de Cinderfall', type: 'Rifle Asalto', damage: '1d8', damageType: 'Radiante', range: '100/300', weight: 6.0, price: 0, rarity: 'Legendaria', properties: ['Luz Pura'] },
  { id: 'adar', name: 'ADAR 2-15', type: 'Rifle Asalto', damage: '1d8', damageType: 'Perforante', range: '90/270', weight: 7.0, price: 3000, rarity: 'Civil', properties: ['Modular'] },
  { id: 'm4a1_c', name: 'M4A1 Semi', type: 'Rifle Asalto', damage: '1d8', damageType: 'Perforante', range: '90/270', weight: 6.5, price: 5000, rarity: 'Civil', properties: ['Ergonómica'] },
  { id: 'tx15', name: 'TX-15', type: 'Rifle Asalto', damage: '1d8', damageType: 'Perforante', range: '120/360', weight: 7.5, price: 12000, rarity: 'Caceria', properties: ['Competición'] },
  { id: 'm4a1_t', name: 'M4A1 / Mk18', type: 'Rifle Asalto', damage: '1d8', damageType: 'Perforante', range: '90/270', weight: 6.5, price: 28000, rarity: 'Táctica', properties: ['Modular Bonificada'] },
  { id: 'engranaje_perdido', name: 'El Engranaje Perdido', type: 'Rifle Asalto', damage: '1d8', damageType: 'Perforante', range: '90/270', weight: 6.5, price: 0, rarity: 'Legendaria', properties: ['Canalizar'] },
  { id: 'hk416', name: 'HK 416', type: 'Rifle Asalto', damage: '1d8', damageType: 'Perforante', range: '100/300', weight: 7.5, price: 40000, rarity: 'Táctica', properties: ['Fiabilidad'] },
  { id: 'martillo_thor', name: 'El Martillo de Thor', type: 'Rifle Asalto', damage: '1d8', damageType: 'Perforante', range: '100/300', weight: 7.5, price: 0, rarity: 'Legendaria', properties: ['Tiro de Rayo'] },
  { id: 'asval', name: 'AS VAL (9x39)', type: 'Rifle Asalto', damage: '2d6', damageType: 'Perforante', range: '50/150', weight: 5.5, price: 55000, rarity: 'Táctica', properties: ['Fantasma'] },
  { id: 'ultimo_aliento', name: 'El Último Aliento del Traidor', type: 'Rifle Asalto', damage: '2d6', damageType: 'Perforante', range: '50/150', weight: 5.5, price: 0, rarity: 'Legendaria', properties: ['Asesino'] },
  { id: 'fnscar_ca', name: 'FN SCAR-H (Caza)', type: 'Rifle Asalto', damage: '1d12', damageType: 'Perforante', range: '120/360', weight: 8.0, price: 18000, rarity: 'Caceria', properties: ['Potente'] },
  { id: 'fnscar_t', name: 'FN SCAR-H (Táctico)', type: 'Rifle Asalto', damage: '1d12', damageType: 'Perforante', range: '120/360', weight: 8.2, price: 42000, rarity: 'Táctica', properties: ['Calibre Batalla'] },
  { id: 'domador_bestias', name: 'El Domador de Bestias', type: 'Rifle Asalto', damage: '1d12', damageType: 'Perforante', range: '120/360', weight: 8.2, price: 0, rarity: 'Legendaria', properties: ['Cazador'] },
  { id: 'sks', name: 'SKS', type: 'Rifle Asalto', damage: '2d6', damageType: 'Perforante', range: '80/240', weight: 8.5, price: 900, rarity: 'Civil', properties: ['Indestructible'] },
  { id: 'aug', name: 'AUG A3', type: 'Rifle Asalto', damage: '1d8', damageType: 'Perforante', range: '90/270', weight: 8.0, price: 33000, rarity: 'Táctica', properties: ['Bullpup'] },
  { id: 'czbren', name: 'CZ Bren 2', type: 'Rifle Asalto', damage: '1d8', damageType: 'Perforante', range: '100/300', weight: 6.8, price: 38000, rarity: 'Táctica', properties: ['Suave'] },

  // --- LMG ---
  { id: 'rpk16', name: 'RPK-16', type: 'LMG', damage: '1d8', damageType: 'Perforante', range: '100/300', weight: 10.0, price: 35000, rarity: 'Táctica', properties: ['Híbrido'] },
  { id: 'tambor_infinito', name: 'El Tambor Infinito', type: 'LMG', damage: '1d8', damageType: 'Perforante', range: '100/300', weight: 10.0, price: 0, rarity: 'Legendaria', properties: ['Regeneración'] },
  { id: 'pkm', name: 'PKM / PKP', type: 'LMG', damage: '1d12', damageType: 'Perforante', range: '150/450', weight: 17.0, price: 70000, rarity: 'Táctica', properties: ['Supresión'] },
  { id: 'corazon_oso', name: 'El Corazón del Oso', type: 'LMG', damage: '1d12', damageType: 'Perforante', range: '150/450', weight: 17.0, price: 0, rarity: 'Legendaria', properties: ['Resistencia'] },
  { id: 'mg3', name: 'MG3', type: 'LMG', damage: '1d12', damageType: 'Perforante', range: '150/450', weight: 25.0, price: 85000, rarity: 'Táctica', properties: ['Terror'] },
  { id: 'm249', name: 'M249 SAW', type: 'LMG', damage: '1d8', damageType: 'Perforante', range: '100/300', weight: 17.0, price: 45000, rarity: 'Táctica', properties: ['Volumen'] },
  { id: 'sierra_implacable', name: 'La Sierra Implacable', type: 'LMG', damage: '1d8', damageType: 'Perforante', range: '100/300', weight: 17.0, price: 0, rarity: 'Legendaria', properties: ['Infinita'] },
  { id: 'rpd', name: 'RPD', type: 'LMG', damage: '2d6', damageType: 'Perforante', range: '100/300', weight: 16.0, price: 25000, rarity: 'Táctica', properties: ['Fiable'] },
  { id: 'eco_jungla', name: 'El Eco de la Jungla', type: 'LMG', damage: '2d6', damageType: 'Perforante', range: '100/300', weight: 16.0, price: 0, rarity: 'Legendaria', properties: ['Invisible'] },
  { id: 'ultimax', name: 'Ultimax 100', type: 'LMG', damage: '1d8', damageType: 'Perforante', range: '100/300', weight: 11.0, price: 50000, rarity: 'Táctica', properties: ['Retroceso Constante'] },
  { id: 'pulso_constante', name: 'El Pulso Constante', type: 'LMG', damage: '1d8', damageType: 'Perforante', range: '100/300', weight: 11.0, price: 0, rarity: 'Legendaria', properties: ['Foco'] },

  // --- DMR / SNIPER ---
  { id: 'svd_c', name: 'SVD (Tigr)', type: 'DMR', damage: '1d12', damageType: 'Perforante', range: '200/600', weight: 8.5, price: 9000, rarity: 'Caceria', properties: ['Letal'] },
  { id: 'svd_t', name: 'SVD', type: 'DMR', damage: '1d12', damageType: 'Perforante', range: '250/750', weight: 9.5, price: 16000, rarity: 'Táctica', properties: ['Fiable'] },
  { id: 'ojo_dragon', name: 'El Ojo del Dragón', type: 'DMR', damage: '1d12', damageType: 'Perforante', range: '250/750', weight: 9.5, price: 0, rarity: 'Legendaria', properties: ['Visión'] },
  { id: 'm1a_c', name: 'M1A (Civil)', type: 'DMR', damage: '1d12', damageType: 'Perforante', range: '200/600', weight: 10.0, price: 3800, rarity: 'Civil', properties: ['Pesado'] },
  { id: 'm1a_ca', name: 'M1A (Caza)', type: 'DMR', damage: '1d12', damageType: 'Perforante', range: '200/600', weight: 9.0, price: 7000, rarity: 'Caceria', properties: ['Ergonómico'] },
  { id: 'eco_colina', name: 'El Eco de la Colina', type: 'DMR', damage: '1d12', damageType: 'Perforante', range: '200/600', weight: 9.0, price: 0, rarity: 'Legendaria', properties: ['Ventrílocuo'] },
  { id: 'sr25', name: 'SR-25', type: 'DMR', damage: '1d12', damageType: 'Perforante', range: '200/600', weight: 10.0, price: 45000, rarity: 'Táctica', properties: ['Silencioso'] },
  { id: 'marcador_destinos', name: 'El Marcador de Destinos', type: 'DMR', damage: '1d12', damageType: 'Perforante', range: '200/600', weight: 10.0, price: 0, rarity: 'Legendaria', properties: ['Marcar'] },
  { id: 'rsass', name: 'RSASS', type: 'DMR', damage: '1d12', damageType: 'Perforante', range: '250/750', weight: 11.0, price: 50000, rarity: 'Táctica', properties: ['Sub-MOA'] },
  { id: 'relojero', name: 'El Relojero', type: 'DMR', damage: '1d12', damageType: 'Perforante', range: '250/750', weight: 11.0, price: 0, rarity: 'Legendaria', properties: ['Alerta'] },
  { id: 'g28', name: 'G28', type: 'DMR', damage: '1d12', damageType: 'Perforante', range: '200/600', weight: 13.0, price: 52000, rarity: 'Táctica', properties: ['Óptica'] },
  { id: 'm700_c', name: 'M700 (Civil)', type: 'Sniper', damage: '1d12', damageType: 'Perforante', range: '200/600', weight: 7.0, price: 2500, rarity: 'Civil', properties: ['Simple'] },
  { id: 'm700_ca', name: 'M700 (Caza)', type: 'Sniper', damage: '1d12', damageType: 'Perforante', range: '200/600', weight: 7.5, price: 5000, rarity: 'Caceria', properties: ['Flotante'] },
  { id: 'm700_t', name: 'M700 (Táctico)', type: 'Sniper', damage: '1d12', damageType: 'Perforante', range: '200/600', weight: 12.0, price: 12000, rarity: 'Táctica', properties: ['Militar'] },
  { id: 'aliento_congelado', name: 'El Aliento Congelado', type: 'Sniper', damage: '1d12', damageType: 'Perforante', range: '200/600', weight: 7.5, price: 0, rarity: 'Legendaria', properties: ['Parálisis'] },
  { id: 'mosin', name: 'Mosin-Nagant', type: 'Sniper', damage: '1d12', damageType: 'Perforante', range: '200/600', weight: 8.8, price: 700, rarity: 'Civil', properties: ['Indestructible'] },
  { id: 'ultimo_zumbido', name: 'El Último Zumbido', type: 'Sniper', damage: '1d12', damageType: 'Perforante', range: '200/600', weight: 8.0, price: 0, rarity: 'Legendaria', properties: ['Fantasma Ignora Cobertura'] },
  { id: 't5000', name: 'T-5000', type: 'Sniper', damage: '2d10', damageType: 'Perforante', range: '300/900', weight: 13.0, price: 35000, rarity: 'Táctica', properties: ['Quirúrgico'] },
  { id: 'ecuacion_imposible', name: 'La Ecuación Imposible', type: 'Sniper', damage: '2d10', damageType: 'Perforante', range: '300/900', weight: 13.0, price: 0, rarity: 'Legendaria', properties: ['Cálculo'] },
  { id: 'dvl10', name: 'DVL-10', type: 'Sniper', damage: '1d12', damageType: 'Perforante', range: '200/600', weight: 11.0, price: 48000, rarity: 'Táctica', properties: ['Fantasma Urbano'] },
  { id: 'vacio_acustico', name: 'El Vacío Acústico', type: 'Sniper', damage: '1d12', damageType: 'Perforante', range: '200/600', weight: 11.0, price: 0, rarity: 'Legendaria', properties: ['Silencio'] },
  { id: 'vss', name: 'VSS Vintorez (9x39)', type: 'Sniper', damage: '2d6', damageType: 'Perforante', range: '100/300', weight: 5.7, price: 52000, rarity: 'Táctica', properties: ['Subsónico'] },
  { id: 'silenciador_verdad', name: 'El Silenciador de la Verdad', type: 'Sniper', damage: '2d6', damageType: 'Perforante', range: '100/300', weight: 5.7, price: 0, rarity: 'Legendaria', properties: ['Olvido'] },
  { id: 'sv98', name: 'SV-98', type: 'Sniper', damage: '1d12', damageType: 'Perforante', range: '250/750', weight: 13.0, price: 28000, rarity: 'Táctica', properties: ['Robusto'] },
  { id: 'axmc', name: 'AXMC (.338)', type: 'Sniper', damage: '2d10', damageType: 'Perforante', range: '600/1800', weight: 15.0, price: 90000, rarity: 'Táctica', properties: ['Alcance Extremo'] },
  { id: 'winchester70', name: 'Winchester 70', type: 'Sniper', damage: '1d12', damageType: 'Perforante', range: '200/600', weight: 8.0, price: 4500, rarity: 'Caceria', properties: ['Fiable'] },
  { id: 'susurro_viento', name: 'El Susurro del Viento', type: 'Sniper', damage: '1d12', damageType: 'Perforante', range: '∞', weight: 3.0, price: 0, rarity: 'Legendaria', properties: ['Sin Caída'] },

  // --- ANTI-MATERIAL ---
  { id: 'ash12', name: 'Ash-12 (12.7x55)', type: 'Rifle Asalto', damage: '4d10', damageType: 'Perforante', range: '50/150', weight: 13.0, price: 60000, rarity: 'Táctica', properties: ['Urbano'] },
  { id: 'matador_gigantes', name: 'El Matador de Gigantes', type: 'Sniper', damage: '4d10', damageType: 'Perforante', range: '50/150', weight: 13.0, price: 0, rarity: 'Legendaria', properties: ['Cazador'] },
  { id: 'osv96', name: 'OSV-96 (12.7x108)', type: 'Sniper', damage: '2d20', damageType: 'Perforante', range: '500/1500', weight: 28.0, price: 120000, rarity: 'Táctica', properties: ['Plegable'] },
  { id: 'llave_maestra', name: 'La Llave Maestra', type: 'Sniper', damage: '2d20', damageType: 'Perforante', range: '500/1500', weight: 28.0, price: 0, rarity: 'Legendaria', properties: ['Demolición'] },
  { id: 'barrett', name: 'Barrett M82 (.50)', type: 'Sniper', damage: '2d20', damageType: 'Perforante', range: '600/1800', weight: 30.0, price: 150000, rarity: 'Táctica', properties: ['Anti-Estructura'] },
  { id: 'rompemundos', name: 'El Rompemundos', type: 'Sniper', damage: '2d20', damageType: 'Perforante', range: '600/1800', weight: 30.0, price: 0, rarity: 'Legendaria', properties: ['Onda'] },
  { id: 'ptrs41', name: 'PTRS-41', type: 'Sniper', damage: '3d10', damageType: 'Perforante', range: '300/900', weight: 46.0, price: 20000, rarity: 'Táctica', properties: ['Obsoleto'] },
  { id: 'puno_hierro', name: 'El Puño de Hierro', type: 'Sniper', damage: '3d10', damageType: 'Perforante', range: '300/900', weight: 46.0, price: 0, rarity: 'Legendaria', properties: ['Perforador'] },
  { id: 'ntw20', name: 'NTW-20 (20mm)', type: 'Sniper', damage: '4d12', damageType: 'Perforante', range: '500/1500', weight: 68.0, price: 180000, rarity: 'Táctica', properties: ['Explosivo'] },
  { id: 'juicio_final', name: 'El Juicio Final', type: 'Sniper', damage: '4d12', damageType: 'Plasma', range: '500/1500', weight: 68.0, price: 0, rarity: 'Legendaria', properties: ['Plasma'] },

  // --- MELEE ---
  { id: 'cuchillo', name: 'Cuchillo / Machete', type: 'Melee', damage: '1d4', damageType: 'Cortante', range: '5', weight: 1.0, price: 50, rarity: 'Civil', properties: ['Herramienta'] },
  { id: 'machete_pesado', name: 'Machete Pesado', type: 'Melee', damage: '1d6', damageType: 'Cortante', range: '5', weight: 3.0, price: 150, rarity: 'Civil', properties: ['Despejar'] },
  { id: 'kukri', name: 'Kukri de Caza', type: 'Melee', damage: '1d6', damageType: 'Cortante', range: '5', weight: 2.0, price: 400, rarity: 'Caceria', properties: ['Corte Profundo'] },
  { id: 'hacha_palanca', name: 'Hacha / Palanca', type: 'Melee', damage: '1d6', damageType: 'Contundente', range: '5', weight: 4.0, price: 80, rarity: 'Civil', properties: ['Rompe Puertas'] },
  { id: 'espadon_chatarra', name: 'Espadón de Chatarra', type: 'Melee', damage: '1d12', damageType: 'Cortante', range: '5', weight: 12.0, price: 200, rarity: 'Civil', properties: ['Lento'] },
  { id: 'lanza_tuberia', name: 'Lanza de Tubería', type: 'Melee', damage: '1d8', damageType: 'Perforante', range: '10', weight: 5.0, price: 50, rarity: 'Civil', properties: ['Alcance'] },
  { id: 'lanza_caza', name: 'Lanza de Caza', type: 'Melee', damage: '1d8', damageType: 'Perforante', range: '10', weight: 4.0, price: 600, rarity: 'Caceria', properties: ['Parada'] },
  { id: 'sable', name: 'Sable de Caballería', type: 'Melee', damage: '1d8', damageType: 'Cortante', range: '5', weight: 3.0, price: 800, rarity: 'Civil', properties: ['Tajo'] },
  { id: 'kabar', name: 'KABAR', type: 'Melee', damage: '1d6', damageType: 'Perforante', range: '5', weight: 1.0, price: 300, rarity: 'Táctica', properties: ['Militar'] },
  { id: 'hacha_tactica', name: 'Hacha Táctica', type: 'Melee', damage: '1d6', damageType: 'Cortante', range: '5', weight: 2.0, price: 400, rarity: 'Táctica', properties: ['Rápida'] },
  { id: 'cuchillo_trinchera', name: 'Cuchillo de Trinchera', type: 'Melee', damage: '1d4', damageType: 'Mixto', range: '5', weight: 1.5, price: 500, rarity: 'Táctica', properties: ['Nudillos'] },
  { id: 'gladius', name: 'Espada Corta "Gladius"', type: 'Melee', damage: '1d6', damageType: 'Perforante', range: '5', weight: 2.5, price: 1200, rarity: 'Táctica', properties: ['CQC'] },
  { id: 'katana', name: 'Katana Táctica', type: 'Melee', damage: '1d8', damageType: 'Cortante', range: '5', weight: 3.0, price: 2500, rarity: 'Táctica', properties: ['Versátil'] },
  { id: 'fragmento_cinderfall', name: 'Fragmento de Cinderfall', type: 'Melee', damage: '1d4', damageType: 'Fuerza', range: '5', weight: 1.0, price: 0, rarity: 'Legendaria', properties: ['Anómalo'] },
  { id: 'ecos_vacio', name: 'Ecos del Vacío', type: 'Melee', damage: '1d8', damageType: 'Necrótico', range: '5', weight: 2.0, price: 0, rarity: 'Legendaria', properties: ['Vampirismo'] },
  { id: 'divisor', name: 'El Divisor', type: 'Melee', damage: '2d6', damageType: 'Cortante', range: '5', weight: 15.0, price: 0, rarity: 'Legendaria', properties: ['Rompe-Escudos'] },
  { id: 'aguja_cielo', name: 'Aguja del Cielo', type: 'Melee', damage: '1d8', damageType: 'Eléctrico', range: '15', weight: 4.0, price: 0, rarity: 'Legendaria', properties: ['Relámpago'] },

  // --- MELEE FALTANTES ---
  { id: 'bate_porra', name: 'Bate / Porra', type: 'Melee', damage: '1d6', damageType: 'Contundente', range: '5', weight: 3.0, price: 20, rarity: 'Civil', properties: ['Ligera'] },
  { id: 'espada_larga', name: 'Espada Larga', type: 'Melee', damage: '1d8', damageType: 'Cortante', range: '5', weight: 3.0, price: 500, rarity: 'Táctica', properties: ['Versátil'] },
  { id: 'martillo_guerra', name: 'Martillo de Guerra', type: 'Melee', damage: '1d8', damageType: 'Contundente', range: '5', weight: 5.0, price: 250, rarity: 'Táctica', properties: ['Versátil'] },
  { id: 'gran_espada', name: 'Gran Espada', type: 'Melee', damage: '2d6', damageType: 'Cortante', range: '5', weight: 6.0, price: 1200, rarity: 'Táctica', properties: ['Pesada'] },
  { id: 'motosierra', name: 'Motosierra', type: 'Melee', damage: '2d6', damageType: 'Cortante', range: '5', weight: 15.0, price: 2000, rarity: 'Táctica', properties: ['Pesada', 'Ruidosa'] },

  // --- SMG FALTANTES ---
  { id: 'pp19_bizon', name: 'PP-19 Bizon', type: 'Subfusil', damage: '1d6', damageType: 'Perforante', range: '40/120', weight: 5.0, price: 1800, rarity: 'Táctica', properties: ['Auto', 'Fiable'] },

  // --- ESCOPETA FALTANTE ---
  { id: 'aa12', name: 'AA-12', type: 'Escopeta', damage: '1d8', damageType: 'Perforante', range: '20/60', weight: 10.0, price: 12000, rarity: 'Táctica', properties: ['Auto', 'Bajo Retroceso'] },

  // --- DMR/SNIPER FALTANTE ---
  { id: 'awm', name: 'AWM', type: 'Sniper', damage: '2d10', damageType: 'Perforante', range: '400/1200', weight: 15.0, price: 15000, rarity: 'Táctica', properties: ['Quirúrgico'] },

  // --- LMG FALTANTE ---
  { id: 'm60', name: 'M60', type: 'LMG', damage: '1d12', damageType: 'Perforante', range: '200/600', weight: 23.0, price: 7000, rarity: 'Táctica', properties: ['Supresión', 'Terror'] },

  // --- ANTI-MATERIAL FALTANTES ---
  { id: 'ksvk', name: 'KSVK 12.7', type: 'Sniper', damage: '4d10', damageType: 'Perforante', range: '500/1500', weight: 26.0, price: 25000, rarity: 'Táctica', properties: ['Perforante Superior'] },
  { id: 'kpvt', name: 'KPVT 14.5mm', type: 'LMG', damage: '4d12', damageType: 'Perforante', range: '1000/3000', weight: 110.0, price: 60000, rarity: 'Táctica', properties: ['Impacto Masivo', 'Incontrolable'] },

  // --- LANZADORES ---
  { id: 'rpg7', name: 'RPG-7', type: 'Lanzador', damage: '8d6', damageType: 'Explosivo', range: '150/450', weight: 15.0, price: 8000, rarity: 'Táctica', properties: ['Radio 20 pies'] },
  { id: 'm72_law', name: 'M72 LAW', type: 'Lanzador', damage: '6d6', damageType: 'Explosivo', range: '100/300', weight: 5.0, price: 3000, rarity: 'Táctica', properties: ['Desechable'] },
  { id: 'carl_gustav', name: 'Carl Gustav', type: 'Lanzador', damage: '10d6', damageType: 'Explosivo', range: '200/600', weight: 19.0, price: 15000, rarity: 'Táctica', properties: ['Recargable'] },
  { id: 'gp25', name: 'Lanzagranadas GP-25', type: 'Lanzador', damage: '4d6', damageType: 'Explosivo', range: '40/120', weight: 3.0, price: 2000, rarity: 'Táctica', properties: ['Bajo cañón'] },
  { id: 'm203', name: 'Lanzagranadas M203', type: 'Lanzador', damage: '4d6', damageType: 'Explosivo', range: '40/120', weight: 3.0, price: 2500, rarity: 'Táctica', properties: ['Bajo cañón'] },
  { id: 'milkor_mgl', name: 'Milkor MGL', type: 'Lanzador', damage: '4d6', damageType: 'Explosivo', range: '40/120', weight: 13.0, price: 12000, rarity: 'Táctica', properties: ['Revólver 6 granadas'] },

  // --- ARMAS ESPECIALES ---
  { id: 'lanzallamas', name: 'Lanzallamas', type: 'Especial', damage: '3d6', damageType: 'Fuego', range: '15 (Cono)', weight: 20.0, price: 5000, rarity: 'Táctica', properties: ['Fuego', 'Salv DES 13'] },
  { id: 'arco_compuesto', name: 'Arco Compuesto', type: 'Especial', damage: '1d8', damageType: 'Perforante', range: '80/320', weight: 3.0, price: 500, rarity: 'Civil', properties: ['Silencio Total'] },
  { id: 'ballesta_tactica', name: 'Ballesta Táctica', type: 'Especial', damage: '1d10', damageType: 'Perforante', range: '100/400', weight: 8.0, price: 1200, rarity: 'Táctica', properties: ['Silencio Total', 'Recarga Constante'] },
  { id: 'taser_x26', name: 'Taser X26', type: 'Especial', damage: '0', damageType: 'Eléctrico', range: '15', weight: 1.0, price: 800, rarity: 'Táctica', properties: ['Paraliza (Salv CON 14)'] },
  { id: 'mina_ap', name: 'Mina Antipersonal', type: 'Especial', damage: '4d6', damageType: 'Perforante', range: '15 (Radio)', weight: 2.0, price: 600, rarity: 'Táctica', properties: ['Trampa', 'Salv DES 15'] },
  { id: 'c4', name: 'C4 (1 bloque)', type: 'Especial', damage: '6d6', damageType: 'Explosivo', range: '20 (Radio)', weight: 1.0, price: 1000, rarity: 'Táctica', properties: ['Control remoto', 'Salv DES 15'] },
  { id: 'granada_emp', name: 'Granada EMP', type: 'Especial', damage: '0', damageType: 'Eléctrico', range: '30 (Radio)', weight: 1.0, price: 2000, rarity: 'Táctica', properties: ['Deshabilita electrónica 10 min'] },

  // --- ANÓMALAS ---
  { id: 'singularidad', name: 'La Singularidad Portátil', type: 'Anomala', damage: '3d8', damageType: 'Fuerza', range: '60', weight: 8.0, price: 0, rarity: 'Anomala', properties: ['Gravedad'] },
  { id: 'eco_olvido', name: 'Eco del Olvido', type: 'Anomala', damage: '2d6', damageType: 'Psíquico', range: '60', weight: 3.0, price: 0, rarity: 'Anomala', properties: ['Olvido'] },
  { id: 'lanzador_cinetico', name: 'Lanzador Cinético', type: 'Anomala', damage: '2d8', damageType: 'Contundente', range: '40', weight: 6.0, price: 0, rarity: 'Anomala', properties: ['Infinita'] },
  { id: 'espada_tormenta', name: 'Espada de Tormenta Resonante', type: 'Anomala', damage: '1d8', damageType: 'Eléctrico', range: '5', weight: 3.0, price: 0, rarity: 'Anomala', properties: ['Arco Voltaico'] },
  { id: 'corazon_helado', name: 'El Corazón Helado del Reich', type: 'Anomala', damage: '3d6', damageType: 'Frío', range: '15 (Cono)', weight: 5.0, price: 0, rarity: 'Anomala', properties: ['Congelar'] },
];
